import {Merge, Partial} from "../../../lang";
import {VirtualElementAttributes} from "./TypedVirtualElementAttributes";
import {VirtualElementGlobalEventHandlers} from "./VirtualElementGlobalEventHandlers";
import {HTMLVirtualElementAttributes} from "./HTMLIntrinsicElements";

export interface SVGVirtualElementAttributes<T> extends VirtualElementAttributes, VirtualElementGlobalEventHandlers {
    class: string;
    className: string;
    style: string;
    classList: Array<string>;
    children: Array<T>;

    // namespaces
    xmlns: string;
    xmlnsXlink: string;
    xmlnsSvgjs: string;
    'xlinkActuate': string;
    'xlinkArcrole': string;
    'xlinkHref': string;
    'xlinkRole': string;
    'xlinkShow': string;
    'xlinkTitle': string;
    'xlinkType': string;
    'xmlBase': string;
    'xmlLang': string;
    'xmlSpace': string;
    version: string;

    // DOM string value support

    // attributes

    'accent-height': string|number|boolean;
    'accumulate': string|number|boolean;
    'additive': string|number|boolean;
    'alignment-baseline': string|number|boolean;
    'allowReorder': string|number|boolean;
    'alphabetic': string|number|boolean;
    'amplitude': string|number|boolean;
    'arabic-form': string|number|boolean;
    'ascent': string|number|boolean;
    'attributeName': string|number|boolean;
    'attributeType': string|number|boolean;
    'autoReverse': string|number|boolean;
    'azimuth': string|number|boolean;
    'baseFrequency': string|number|boolean;
    'baseline-shift': string|number|boolean;
    'baseProfile': string|number|boolean;
    'bbox': string|number|boolean;
    'begin': string|number|boolean;
    'bias': string|number|boolean;
    'by': string|number|boolean;
    'calcMode': string|number|boolean;
    'cap-height': string|number|boolean;
    'clip': string|number|boolean;
    'clipPathUnits': string|number|boolean;
    'clip-path': string|number|boolean;
    'clip-rule': string|number|boolean;
    'color': string|number|boolean;
    'color-interpolation': string|number|boolean;
    'color-interpolation-filters': string|number|boolean;
    'color-profile': string|number|boolean;
    'color-rendering': string|number|boolean;
    'contentScriptType': string|number|boolean;
    'contentStyleType': string|number|boolean;
    'cursor': string|number|boolean;
    'cx': string|number|boolean;
    'cy': string|number|boolean;
    'd': string|number|boolean;
    'decelerate': string|number|boolean;
    'descent': string|number|boolean;
    'diffuseConstant': string|number|boolean;
    'direction': string|number|boolean;
    'display': string|number|boolean;
    'divisor': string|number|boolean;
    'dominant-baseline': string|number|boolean;
    'dur': string|number|boolean;
    'dx': string|number|boolean;
    'dy': string|number|boolean;
    'edgeMode': string|number|boolean;
    'elevation': string|number|boolean;
    'enable-background': string|number|boolean;
    'end': string|number|boolean;
    'exponent': string|number|boolean;
    'externalResourcesRequired': string|number|boolean;
    'fill': string|number|boolean;
    'fill-opacity': string|number|boolean;
    'fill-rule': string|number|boolean;
    'filter': string|number|boolean;
    'filterRes': string|number|boolean;
    'filterUnits': string|number|boolean;
    'flood-color': string|number|boolean;
    'flood-opacity': string|number|boolean;
    'family': string|number|boolean;
    'size': string|number|boolean;
    'font-family': string|number|boolean;
    'font-size': string|number|boolean;
    'font-size-adjust': string|number|boolean;
    'font-stretch': string|number|boolean;
    'font-style': string|number|boolean;
    'font-variant': string|number|boolean;
    'font-weight': string|number|boolean;
    'format': string|number|boolean;
    'from': string|number|boolean;
    'fx': string|number|boolean;
    'fy': string|number|boolean;
    'g1': string|number|boolean;
    'g2': string|number|boolean;
    'glyph-name': string|number|boolean;
    'glyph-orientation-horizontal': string|number|boolean;
    'glyph-orientation-vertical': string|number|boolean;
    'glyphRef': string|number|boolean;
    'gradientTransform': string|number|boolean;
    'gradientUnits': string|number|boolean;
    'hanging': string|number|boolean;
    'height': string|number|boolean;
    'href': string|number|boolean;
    'horiz-adv-x': string|number|boolean;
    'horiz-origin-x': string|number|boolean;
    'id': string|number|boolean;
    'ideographic': string|number|boolean;
    'image-rendering': string|number|boolean;
    'in': string|number|boolean;
    'in2': string|number|boolean;
    'intercept': string|number|boolean;
    'k': string|number|boolean;
    'k1': string|number|boolean;
    'k2': string|number|boolean;
    'k3': string|number|boolean;
    'k4': string|number|boolean;
    'kernelMatrix': string|number|boolean;
    'kernelUnitLength': string|number|boolean;
    'kerning': string|number|boolean;
    'keyPoints': string|number|boolean;
    'keySplines': string|number|boolean;
    'keyTimes': string|number|boolean;
    'lang': string|number|boolean;
    'lengthAdjust': string|number|boolean;
    'letter-spacing': string|number|boolean;
    'lighting-color': string|number|boolean;
    'limitingConeAngle': string|number|boolean;
    'local': string|number|boolean;
    'marker-end': string|number|boolean;
    'marker-mid': string|number|boolean;
    'marker-start': string|number|boolean;
    'markerHeight': string|number|boolean;
    'markerUnits': string|number|boolean;
    'markerWidth': string|number|boolean;
    'mask': string|number|boolean;
    'maskContentUnits': string|number|boolean;
    'maskUnits': string|number|boolean;
    'mathematical': string|number|boolean;
    'max': string|number|boolean;
    'media': string|number|boolean;
    'method': string|number|boolean;
    'min': string|number|boolean;
    'mode': string|number|boolean;
    'name': string|number|boolean;
    'numOctaves': string|number|boolean;
    'offset': string|number|boolean;
    'opacity': string|number|boolean;
    'operator': string|number|boolean;
    'order': string|number|boolean;
    'orient': string|number|boolean;
    'orientation': string|number|boolean;
    'origin': string|number|boolean;
    'overflow': string|number|boolean;
    'overline-position': string|number|boolean;
    'overline-thickness': string|number|boolean;
    'panose-1': string|number|boolean;
    'paint-order': string|number|boolean;
    'pathLength': string|number|boolean;
    'patternContentUnits': string|number|boolean;
    'patternTransform': string|number|boolean;
    'patternUnits': string|number|boolean;
    'pointer-events': string|number|boolean;
    'points': string|number|boolean;
    'pointsAtX': string|number|boolean;
    'pointsAtY': string|number|boolean;
    'pointsAtZ': string|number|boolean;
    'preserveAlpha': string|number|boolean;
    'preserveAspectRatio': string|number|boolean;
    'primitiveUnits': string|number|boolean;
    'r': string|number|boolean;
    'radius': string|number|boolean;
    'refX': string|number|boolean;
    'refY': string|number|boolean;
    'rendering-intent': string|number|boolean;
    'repeatCount': string|number|boolean;
    'repeatDur': string|number|boolean;
    'requiredExtensions': string|number|boolean;
    'requiredFeatures': string|number|boolean;
    'restart': string|number|boolean;
    'result': string|number|boolean;
    'rotate': string|number|boolean;
    'rx': string|number|boolean;
    'ry': string|number|boolean;
    'scale': string|number|boolean;
    'seed': string|number|boolean;
    'shape-rendering': string|number|boolean;
    'slope': string|number|boolean;
    'spacing': string|number|boolean;
    'specularConstant': string|number|boolean;
    'specularExponent': string|number|boolean;
    'speed': string|number|boolean;
    'spreadMethod': string|number|boolean;
    'startOffset': string|number|boolean;
    'stdDeviation': string|number|boolean;
    'stemh': string|number|boolean;
    'stemv': string|number|boolean;
    'stitchTiles': string|number|boolean;
    'stop-color': string|number|boolean;
    'stop-opacity': string|number|boolean;
    'strikethrough-position': string|number|boolean;
    'strikethrough-thickness': string|number|boolean;
    'string|number|boolean': string|number|boolean;
    'stroke': string|number|boolean;
    'stroke-dasharray': string|number|boolean;
    'stroke-dashoffset': string|number|boolean;
    'stroke-linecap': string|number|boolean;
    'stroke-linejoin': string|number|boolean;
    'stroke-miterlimit': string|number|boolean;
    'stroke-opacity': string|number|boolean;
    'stroke-width': string|number|boolean;
    'surfaceScale': string|number|boolean;
    'systemLanguage': string|number|boolean;
    'tabindex': string|number|boolean;
    'tableValues': string|number|boolean;
    'target': string|number|boolean;
    'targetX': string|number|boolean;
    'targetY': string|number|boolean;
    'text-anchor': string|number|boolean;
    'text-decoration': string|number|boolean;
    'text-rendering': string|number|boolean;
    'textLength': string|number|boolean;
    'to': string|number|boolean;
    'transform': string|number|boolean;
    'type': string|number|boolean;
    'u1': string|number|boolean;
    'u2': string|number|boolean;
    'underline-position': string|number|boolean;
    'underline-thickness': string|number|boolean;
    'unicode': string|number|boolean;
    'unicode-bidi': string|number|boolean;
    'unicode-range': string|number|boolean;
    'units-per-em': string|number|boolean;
    'v-alphabetic': string|number|boolean;
    'v-hanging': string|number|boolean;
    'v-ideographic': string|number|boolean;
    'v-mathematical': string|number|boolean;
    'values': string|number|boolean;
    'vert-adv-y': string|number|boolean;
    'vert-origin-x': string|number|boolean;
    'vert-origin-y': string|number|boolean;
    'viewBox': string|number|boolean;
    'viewTarget': string|number|boolean;
    'visibility': string|number|boolean;
    'width': string|number|boolean;
    'widths': string|number|boolean;
    'word-spacing': string|number|boolean;
    'writing-mode': string|number|boolean;
    'x': string|number|boolean;
    'x-height': string|number|boolean;
    'x1': string|number|boolean;
    'x2': string|number|boolean;
    'xChannelSelector': string|number|boolean;
    'y': string|number|boolean;
    'y1': string|number|boolean;
    'y2': string|number|boolean;
    'yChannelSelector': string|number|boolean;
    'z': string|number|boolean;
    'zoomAndPan': string|number|boolean;
}

declare global {
    namespace JSX {

        interface IntrinsicElements {
            'a': Merge<Partial<SVGAElement>, Partial<SVGVirtualElementAttributes<SVGAElement>>> |
                Merge<Partial<HTMLAnchorElement>, Partial<HTMLVirtualElementAttributes<HTMLAnchorElement>>>;
            'animate': Merge<Partial<SVGAnimateElement>, Partial<SVGVirtualElementAttributes<SVGAnimateElement>>>;
            'animateMotion': Merge<Partial<SVGAnimateMotionElement>, Partial<SVGVirtualElementAttributes<SVGAnimateMotionElement>>>;
            'animateTransform': Merge<Partial<SVGAnimateTransformElement>, Partial<SVGVirtualElementAttributes<SVGAnimateTransformElement>>>;
            'circle': Merge<Partial<SVGCircleElement>, Partial<SVGVirtualElementAttributes<SVGCircleElement>>>;
            'clipPath': Merge<Partial<SVGClipPathElement>, Partial<SVGVirtualElementAttributes<SVGClipPathElement>>>;
            'color-profile': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'defs': Merge<Partial<SVGDefsElement>, Partial<SVGVirtualElementAttributes<SVGDefsElement>>>;
            'desc': Merge<Partial<SVGDescElement>, Partial<SVGVirtualElementAttributes<SVGDescElement>>>;
            'discard': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'ellipse': Merge<Partial<SVGEllipseElement>, Partial<SVGVirtualElementAttributes<SVGEllipseElement>>>;
            'feBlend': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feColorMatrix': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feComponentTransfer': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feComposite': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feConvolveMatrix': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feDiffuseLighting': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feDisplacementMap': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feDistantLight': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feDropShadow': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feFlood': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feFuncA': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feFuncB': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feFuncG': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feFuncR': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feGaussianBlur': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feImage': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feMerge': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feMergeNode': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feMorphology': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feOffset': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'fePointLight': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feSpecularLighting': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feSpotLight': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feTile': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'feTurbulence': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'filter': Merge<Partial<SVGFilterElement>, Partial<SVGVirtualElementAttributes<SVGFilterElement>>>;
            'foreignObject': Merge<Partial<SVGForeignObjectElement>, Partial<SVGVirtualElementAttributes<SVGForeignObjectElement>>>;
            'g': Merge<Partial<SVGGElement>, Partial<SVGVirtualElementAttributes<SVGGElement>>>;
            'hatch': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'hatchpath': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'image': Merge<Partial<SVGImageElement>, Partial<SVGVirtualElementAttributes<SVGImageElement>>>;
            'line': Merge<Partial<SVGLineElement>, Partial<SVGVirtualElementAttributes<SVGLineElement>>>;
            'linearGradient': Merge<Partial<SVGLinearGradientElement>, Partial<SVGVirtualElementAttributes<SVGLinearGradientElement>>>;
            'marker': Merge<Partial<SVGMarkerElement>, Partial<SVGVirtualElementAttributes<SVGMarkerElement>>>;
            'mask': Merge<Partial<SVGMaskElement>, Partial<SVGVirtualElementAttributes<SVGMaskElement>>>;
            'mesh': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'meshgradient': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'meshpatch': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'meshrow': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'metadata': Merge<Partial<SVGMetadataElement>, Partial<SVGVirtualElementAttributes<SVGMetadataElement>>>;
            'mpath': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'path': Merge<Partial<SVGPathElement>, Partial<SVGVirtualElementAttributes<SVGPathElement>>>;
            'pattern': Merge<Partial<SVGPatternElement>, Partial<SVGVirtualElementAttributes<SVGPatternElement>>>;
            'polygon': Merge<Partial<SVGPolygonElement>, Partial<SVGVirtualElementAttributes<SVGPolygonElement>>>;
            'polyline': Merge<Partial<SVGPolylineElement>, Partial<SVGVirtualElementAttributes<SVGPolylineElement>>>;
            'radialGradient': Merge<Partial<SVGRadialGradientElement>, Partial<SVGVirtualElementAttributes<SVGRadialGradientElement>>>;
            'rect': Merge<Partial<SVGRectElement>, Partial<SVGVirtualElementAttributes<SVGRectElement>>>;
            'script': Merge<Partial<HTMLScriptElement>, Partial<HTMLVirtualElementAttributes<HTMLScriptElement>>> |
                    Merge<Partial<SVGScriptElement>, Partial<SVGVirtualElementAttributes<SVGScriptElement>>>;
            'set': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'solidcolor': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'stop': Merge<Partial<SVGStopElement>, Partial<SVGVirtualElementAttributes<SVGStopElement>>>;
            'style': Merge<Partial<HTMLStyleElement>, Partial<HTMLVirtualElementAttributes<HTMLStyleElement>>> |
                Merge<Partial<SVGStyleElement>, Partial<SVGVirtualElementAttributes<SVGStyleElement>>>;
            'svg': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'switch': Merge<Partial<SVGSwitchElement>, Partial<SVGVirtualElementAttributes<SVGSwitchElement>>>;
            'symbol': Merge<Partial<SVGSymbolElement>, Partial<SVGVirtualElementAttributes<SVGSymbolElement>>>;
            'text': Merge<Partial<SVGTextElement>, Partial<SVGVirtualElementAttributes<SVGTextElement>>>;
            'textPath': Merge<Partial<SVGTextPathElement>, Partial<SVGVirtualElementAttributes<SVGTextPathElement>>>;
            'title': Merge<Partial<SVGTitleElement>, Partial<SVGVirtualElementAttributes<SVGTitleElement>>> |
                Merge<Partial<HTMLTitleElement>, Partial<HTMLVirtualElementAttributes<HTMLTitleElement>>>;
            'tspan': Merge<Partial<SVGTSpanElement>, Partial<SVGVirtualElementAttributes<SVGTSpanElement>>>;
            'unknown': Merge<Partial<SVGElement>, Partial<SVGVirtualElementAttributes<SVGElement>>>;
            'use': Merge<Partial<SVGUseElement>, Partial<SVGVirtualElementAttributes<SVGUseElement>>>;
            'view': Merge<Partial<SVGViewElement>, Partial<SVGVirtualElementAttributes<SVGViewElement>>>;
        }
    }
}