// This file is generated automatically
export const mdcTouchTargetWrapper: string;
export const mdcButton: string;
export const mdcButtonRipple: string;
export const mdcButtonIcon: string;
export const mdcButtonTouch: string;
export const mdcButtonLabel: string;
export const mdcButtonRaised: string;
export const mdcButtonUnelevated: string;
export const mdcButtonOutlined: string;
export const mdcRippleSurfaceTestEdgeVarBug: string;
export const mdcRippleUpgraded: string;
export const mdcRippleUpgradedUnbounded: string;
export const mdcRippleUpgradedForegroundActivation: string;
export const mdcRippleFgRadiusIn: string;
export const mdcRippleFgOpacityIn: string;
export const mdcRippleUpgradedForegroundDeactivation: string;
export const mdcRippleFgOpacityOut: string;
export const mdcRippleUpgradedBackgroundFocused: string;
