orbs:
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  test:
    parallelism: 3
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: Create test results directory
          command: mkdir -p test_results

      - run: yarn test:ci

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test_results
          destination: test_results
workflows:
  unit-test:
    jobs:
      - test