export interface TypedCSSStyleDeclaration {
    alignContent: number | string | null;
    alignItems: number | string | null;
    alignSelf: number | string | null;
    alignmentBaseline: number | string | null;
    animation: string;
    animationDelay: string;
    animationDirection: string;
    animationDuration: string;
    animationFillMode: string;
    animationIterationCount: string;
    animationName: string;
    animationPlayState: string;
    animationTimingFunction: string;
    backfaceVisibility: number | string | null;
    background: number | string | null;
    backgroundAttachment: number | string | null;
    backgroundClip: number | string | null;
    backgroundColor: number | string | null;
    backgroundImage: number | string | null;
    backgroundOrigin: number | string | null;
    backgroundPosition: number | string | null;
    backgroundPositionX: number | string | null;
    backgroundPositionY: number | string | null;
    backgroundRepeat: number | string | null;
    backgroundSize: number | string | null;
    baselineShift: number | string | null;
    border: number | string | null;
    borderBottom: number | string | null;
    borderBottomColor: number | string | null;
    borderBottomLeftRadius: number | string | null;
    borderBottomRightRadius: number | string | null;
    borderBottomStyle: number | string | null;
    borderBottomWidth: number | string | null;
    borderCollapse: number | string | null;
    borderColor: number | string | null;
    borderImage: number | string | null;
    borderImageOutset: number | string | null;
    borderImageRepeat: number | string | null;
    borderImageSlice: number | string | null;
    borderImageSource: number | string | null;
    borderImageWidth: number | string | null;
    borderLeft: number | string | null;
    borderLeftColor: number | string | null;
    borderLeftStyle: number | string | null;
    borderLeftWidth: number | string | null;
    borderRadius: number | string | null;
    borderRight: number | string | null;
    borderRightColor: number | string | null;
    borderRightStyle: number | string | null;
    borderRightWidth: number | string | null;
    borderSpacing: number | string | null;
    borderStyle: number | string | null;
    borderTop: number | string | null;
    borderTopColor: number | string | null;
    borderTopLeftRadius: number | string | null;
    borderTopRightRadius: number | string | null;
    borderTopStyle: number | string | null;
    borderTopWidth: number | string | null;
    borderWidth: number | string | null;
    bottom: number | string | null;
    boxShadow: number | string | null;
    boxSizing: number | string | null;
    breakAfter: number | string | null;
    breakBefore: number | string | null;
    breakInside: number | string | null;
    captionSide: number | string | null;
    clear: number | string | null;
    clip: number | string | null;
    clipPath: number | string | null;
    clipRule: number | string | null;
    color: number | string | null;
    colorInterpolationFilters: number | string | null;
    columnCount: any;
    columnFill: number | string | null;
    columnGap: any;
    columnRule: number | string | null;
    columnRuleColor: any;
    columnRuleStyle: number | string | null;
    columnRuleWidth: any;
    columnSpan: number | string | null;
    columnWidth: any;
    columns: number | string | null;
    content: number | string | null;
    counterIncrement: number | string | null;
    counterReset: number | string | null;
    cssFloat: number | string | null;
    cssText: string;
    cursor: number | string | null;
    direction: number | string | null;
    display: number | string | null;
    dominantBaseline: number | string | null;
    emptyCells: number | string | null;
    enableBackground: number | string | null;
    fill: number | string | null;
    fillOpacity: number | string | null;
    fillRule: number | string | null;
    filter: number | string | null;
    flex: number | string | null;
    flexBasis: number | string | null;
    flexDirection: number | string | null;
    flexFlow: number | string | null;
    flexGrow: number | string | null;
    flexShrink: number | string | null;
    flexWrap: number | string | null;
    floodColor: number | string | null;
    floodOpacity: number | string | null;
    font: number | string | null;
    fontFamily: number | string | null;
    fontFeatureSettings: number | string | null;
    fontSize: number | string | null;
    fontSizeAdjust: number | string | null;
    fontStretch: number | string | null;
    fontStyle: number | string | null;
    fontVariant: number | string | null;
    fontWeight: number | string | null;
    gap: number | string | null;
    glyphOrientationHorizontal: number | string | null;
    glyphOrientationVertical: number | string | null;
    grid: number | string | null;
    gridArea: number | string | null;
    gridAutoColumns: number | string | null;
    gridAutoFlow: number | string | null;
    gridAutoRows: number | string | null;
    gridColumn: number | string | null;
    gridColumnEnd: number | string | null;
    gridColumnGap: number | string | null;
    gridColumnStart: number | string | null;
    gridGap: number | string | null;
    gridRow: number | string | null;
    gridRowEnd: number | string | null;
    gridRowGap: number | string | null;
    gridRowStart: number | string | null;
    gridTemplate: number | string | null;
    gridTemplateAreas: number | string | null;
    gridTemplateColumns: number | string | null;
    gridTemplateRows: number | string | null;
    height: number | string | null;
    imeMode: number | string | null;
    justifyContent: number | string | null;
    justifyItems: number | string | null;
    justifySelf: number | string | null;
    kerning: number | string | null;
    layoutGrid: number | string | null;
    layoutGridChar: number | string | null;
    layoutGridLine: number | string | null;
    layoutGridMode: number | string | null;
    layoutGridType: number | string | null;
    left: number | string | null;
    readonly length: number;
    letterSpacing: number | string | null;
    lightingColor: number | string | null;
    lineBreak: number | string | null;
    lineHeight: number | string | null;
    listStyle: number | string | null;
    listStyleImage: number | string | null;
    listStylePosition: number | string | null;
    listStyleType: number | string | null;
    margin: number | string | null;
    marginBottom: number | string | null;
    marginLeft: number | string | null;
    marginRight: number | string | null;
    marginTop: number | string | null;
    marker: number | string | null;
    markerEnd: number | string | null;
    markerMid: number | string | null;
    markerStart: number | string | null;
    mask: number | string | null;
    maskImage: number | string | null;
    maxHeight: number | string | null;
    maxWidth: number | string | null;
    minHeight: number | string | null;
    minWidth: number | string | null;
    msContentZoomChaining: number | string | null;
    msContentZoomLimit: number | string | null;
    msContentZoomLimitMax: any;
    msContentZoomLimitMin: any;
    msContentZoomSnap: number | string | null;
    msContentZoomSnapPoints: number | string | null;
    msContentZoomSnapType: number | string | null;
    msContentZooming: number | string | null;
    msFlowFrom: number | string | null;
    msFlowInto: number | string | null;
    msFontFeatureSettings: number | string | null;
    msGridColumn: any;
    msGridColumnAlign: number | string | null;
    msGridColumnSpan: any;
    msGridColumns: number | string | null;
    msGridRow: any;
    msGridRowAlign: number | string | null;
    msGridRowSpan: any;
    msGridRows: number | string | null;
    msHighContrastAdjust: number | string | null;
    msHyphenateLimitChars: number | string | null;
    msHyphenateLimitLines: any;
    msHyphenateLimitZone: any;
    msHyphens: number | string | null;
    msImeAlign: number | string | null;
    msOverflowStyle: number | string | null;
    msScrollChaining: number | string | null;
    msScrollLimit: number | string | null;
    msScrollLimitXMax: any;
    msScrollLimitXMin: any;
    msScrollLimitYMax: any;
    msScrollLimitYMin: any;
    msScrollRails: number | string | null;
    msScrollSnapPointsX: number | string | null;
    msScrollSnapPointsY: number | string | null;
    msScrollSnapType: number | string | null;
    msScrollSnapX: number | string | null;
    msScrollSnapY: number | string | null;
    msScrollTranslation: number | string | null;
    msTextCombineHorizontal: number | string | null;
    msTextSizeAdjust: any;
    msTouchAction: number | string | null;
    msTouchSelect: number | string | null;
    msUserSelect: number | string | null;
    msWrapFlow: string;
    msWrapMargin: any;
    msWrapThrough: string;
    objectFit: number | string | null;
    objectPosition: number | string | null;
    opacity: number | string | null;
    order: number | string | null;
    orphans: number | string | null;
    outline: number | string | null;
    outlineColor: number | string | null;
    outlineOffset: number | string | null;
    outlineStyle: number | string | null;
    outlineWidth: number | string | null;
    overflow: number | string | null;
    overflowX: number | string | null;
    overflowY: number | string | null;
    padding: number | string | null;
    paddingBottom: number | string | null;
    paddingLeft: number | string | null;
    paddingRight: number | string | null;
    paddingTop: number | string | null;
    pageBreakAfter: number | string | null;
    pageBreakBefore: number | string | null;
    pageBreakInside: number | string | null;
    readonly parentRule: CSSRule;
    penAction: number | string | null;
    perspective: number | string | null;
    perspectiveOrigin: number | string | null;
    pointerEvents: number | string | null;
    position: number | string | null;
    quotes: number | string | null;
    resize: number | string | null;
    right: number | string | null;
    rotate: number | string | null;
    rowGap: number | string | null;
    rubyAlign: number | string | null;
    rubyOverhang: number | string | null;
    rubyPosition: number | string | null;
    scale: number | string | null;
    scrollBehavior: string;
    stopColor: number | string | null;
    stopOpacity: number | string | null;
    stroke: number | string | null;
    strokeDasharray: number | string | null;
    strokeDashoffset: number | string | null;
    strokeLinecap: number | string | null;
    strokeLinejoin: number | string | null;
    strokeMiterlimit: number | string | null;
    strokeOpacity: number | string | null;
    strokeWidth: number | string | null;
    tableLayout: number | string | null;
    textAlign: number | string | null;
    textAlignLast: number | string | null;
    textAnchor: number | string | null;
    textCombineUpright: number | string | null;
    textDecoration: number | string | null;
    textIndent: number | string | null;
    textJustify: number | string | null;
    textKashida: number | string | null;
    textKashidaSpace: number | string | null;
    textOverflow: number | string | null;
    textShadow: number | string | null;
    textTransform: number | string | null;
    textUnderlinePosition: number | string | null;
    top: number | string | null;
    touchAction: string;
    transform: number | string | null;
    transformOrigin: number | string | null;
    transformStyle: number | string | null;
    transition: string;
    transitionDelay: string;
    transitionDuration: string;
    transitionProperty: string;
    transitionTimingFunction: string;
    translate: number | string | null;
    unicodeBidi: number | string | null;
    userSelect: number | string | null;
    verticalAlign: number | string | null;
    visibility: number | string | null;
    /** @deprecated */
    webkitAlignContent: string;
    /** @deprecated */
    webkitAlignItems: string;
    /** @deprecated */
    webkitAlignSelf: string;
    /** @deprecated */
    webkitAnimation: string;
    /** @deprecated */
    webkitAnimationDelay: string;
    /** @deprecated */
    webkitAnimationDirection: string;
    /** @deprecated */
    webkitAnimationDuration: string;
    /** @deprecated */
    webkitAnimationFillMode: string;
    /** @deprecated */
    webkitAnimationIterationCount: string;
    /** @deprecated */
    webkitAnimationName: string;
    /** @deprecated */
    webkitAnimationPlayState: string;
    /** @deprecated */
    webkitAnimationTimingFunction: string;
    /** @deprecated */
    webkitAppearance: string;
    /** @deprecated */
    webkitBackfaceVisibility: string;
    /** @deprecated */
    webkitBackgroundClip: string;
    /** @deprecated */
    webkitBackgroundOrigin: string;
    /** @deprecated */
    webkitBackgroundSize: string;
    /** @deprecated */
    webkitBorderBottomLeftRadius: string;
    /** @deprecated */
    webkitBorderBottomRightRadius: string;
    webkitBorderImage: number | string | null;
    /** @deprecated */
    webkitBorderRadius: string;
    /** @deprecated */
    webkitBorderTopLeftRadius: string;
    /** @deprecated */
    webkitBorderTopRightRadius: string;
    /** @deprecated */
    webkitBoxAlign: string;
    webkitBoxDirection: number | string | null;
    /** @deprecated */
    webkitBoxFlex: string;
    /** @deprecated */
    webkitBoxOrdinalGroup: string;
    webkitBoxOrient: number | string | null;
    /** @deprecated */
    webkitBoxPack: string;
    /** @deprecated */
    webkitBoxShadow: string;
    /** @deprecated */
    webkitBoxSizing: string;
    webkitColumnBreakAfter: number | string | null;
    webkitColumnBreakBefore: number | string | null;
    webkitColumnBreakInside: number | string | null;
    webkitColumnCount: any;
    webkitColumnGap: any;
    webkitColumnRule: number | string | null;
    webkitColumnRuleColor: any;
    webkitColumnRuleStyle: number | string | null;
    webkitColumnRuleWidth: any;
    webkitColumnSpan: number | string | null;
    webkitColumnWidth: any;
    webkitColumns: number | string | null;
    /** @deprecated */
    webkitFilter: string;
    /** @deprecated */
    webkitFlex: string;
    /** @deprecated */
    webkitFlexBasis: string;
    /** @deprecated */
    webkitFlexDirection: string;
    /** @deprecated */
    webkitFlexFlow: string;
    /** @deprecated */
    webkitFlexGrow: string;
    /** @deprecated */
    webkitFlexShrink: string;
    /** @deprecated */
    webkitFlexWrap: string;
    /** @deprecated */
    webkitJustifyContent: string;
    /** @deprecated */
    webkitMask: string;
    /** @deprecated */
    webkitMaskBoxImage: string;
    /** @deprecated */
    webkitMaskBoxImageOutset: string;
    /** @deprecated */
    webkitMaskBoxImageRepeat: string;
    /** @deprecated */
    webkitMaskBoxImageSlice: string;
    /** @deprecated */
    webkitMaskBoxImageSource: string;
    /** @deprecated */
    webkitMaskBoxImageWidth: string;
    /** @deprecated */
    webkitMaskClip: string;
    /** @deprecated */
    webkitMaskComposite: string;
    /** @deprecated */
    webkitMaskImage: string;
    /** @deprecated */
    webkitMaskOrigin: string;
    /** @deprecated */
    webkitMaskPosition: string;
    /** @deprecated */
    webkitMaskRepeat: string;
    /** @deprecated */
    webkitMaskSize: string;
    /** @deprecated */
    webkitOrder: string;
    /** @deprecated */
    webkitPerspective: string;
    /** @deprecated */
    webkitPerspectiveOrigin: string;
    webkitTapHighlightColor: number | string | null;
    /** @deprecated */
    webkitTextFillColor: string;
    /** @deprecated */
    webkitTextSizeAdjust: string;
    /** @deprecated */
    webkitTextStroke: string;
    /** @deprecated */
    webkitTextStrokeColor: string;
    /** @deprecated */
    webkitTextStrokeWidth: string;
    /** @deprecated */
    webkitTransform: string;
    /** @deprecated */
    webkitTransformOrigin: string;
    /** @deprecated */
    webkitTransformStyle: string;
    /** @deprecated */
    webkitTransition: string;
    /** @deprecated */
    webkitTransitionDelay: string;
    /** @deprecated */
    webkitTransitionDuration: string;
    /** @deprecated */
    webkitTransitionProperty: string;
    /** @deprecated */
    webkitTransitionTimingFunction: string;
    webkitUserModify: number | string | null;
    webkitUserSelect: number | string | null;
    webkitWritingMode: number | string | null;
    whiteSpace: number | string | null;
    widows: number | string | null;
    width: number | string | null;
    wordBreak: number | string | null;
    wordSpacing: number | string | null;
    wordWrap: number | string | null;
    writingMode: number | string | null;
    zIndex: number | string | null;
    zoom: number | string | null;

    // traditional style
    'align-content': string|null;
    'align-items': string|null;
    'align-self': string|null;
    'alignment-baseline': string|null;
    'animation-delay': string;
    'animation-direction': string;
    'animation-duration': string;
    'animation-fill-mode': string;
    'animation-iteration-count': string;
    'animation-name': string;
    'animation-play-state': string;
    'animation-timing-function': string;
    'backface-visibility': string|null;
    'background-attachment': string|null;
    'background-clip': string|null;
    'background-color': string|null;
    'background-image': string|null;
    'background-origin': string|null;
    'background-position': string|null;
    'background-position-x': string|null;
    'background-position-y': string|null;
    'background-repeat': string|null;
    'background-size': string|null;
    'baseline-shift': string|null;
    'border-bottom': string|null;
    'border-bottom-color': string|null;
    'border-bottom-left-radius': string|null;
    'border-bottom-right-radius': string|null;
    'border-bottom-style': string|null;
    'border-bottom-width': string|null;
    'border-collapse': string|null;
    'border-color': string|null;
    'border-image': string|null;
    'border-image-outset': string|null;
    'border-image-repeat': string|null;
    'border-image-slice': string|null;
    'border-image-source': string|null;
    'border-image-width': string|null;
    'border-left': string|null;
    'border-left-color': string|null;
    'border-left-style': string|null;
    'border-left-width': string|null;
    'border-radius': string|null;
    'border-right': string|null;
    'border-right-color': string|null;
    'border-right-style': string|null;
    'border-right-width': string|null;
    'border-spacing': string|null;
    'border-style': string|null;
    'border-top': string|null;
    'border-top-color': string|null;
    'border-top-left-radius': string|null;
    'border-top-right-radius': string|null;
    'border-top-style': string|null;
    'border-top-width': string|null;
    'border-width': string|null;
    'box-shadow': string|null;
    'box-sizing': string|null;
    'break-after': string|null;
    'break-before': string|null;
    'break-inside': string|null;
    'caption-side': string|null;
    'clip-path': string|null;
    'clip-rule': string|null;
    'color-interpolation-filters': string|null;
    'column-count': any;
    'column-fill': string|null;
    'column-gap': any;
    'column-rule': string|null;
    'column-rule-color': any;
    'column-rule-style': string|null;
    'column-rule-width': any;
    'column-span': string|null;
    'column-width': any;
    'counter-increment': string|null;
    'counter-reset': string|null;
    'css-float': string|null;
    'css-text': string;
    'dominant-baseline': string|null;
    'empty-cells': string|null;
    'enable-background': string|null;
    'fill-opacity': string|null;
    'fill-rule': string|null;
    'flex-basis': string|null;
    'flex-direction': string|null;
    'flex-flow': string|null;
    'flex-grow': string|null;
    'flex-shrink': string|null;
    'flex-wrap': string|null;
    'flood-color': string|null;
    'flood-opacity': string|null;
    'font-family': string|null;
    'font-feature-settings': string|null;
    'font-size': string|null;
    'font-size-adjust': string|null;
    'font-stretch': string|null;
    'font-style': string|null;
    'font-variant': string|null;
    'font-weight': string|null;
    'glyph-orientation-horizontal': string|null;
    'glyph-orientation-vertical': string|null;
    'grid-area': string|null;
    'grid-auto-columns': string|null;
    'grid-auto-flow': string|null;
    'grid-auto-rows': string|null;
    'grid-column': string|null;
    'grid-column-end': string|null;
    'grid-column-gap': string|null;
    'grid-column-start': string|null;
    'grid-gap': string|null;
    'grid-row': string|null;
    'grid-row-end': string|null;
    'grid-row-gap': string|null;
    'grid-row-start': string|null;
    'grid-template': string|null;
    'grid-template-areas': string|null;
    'grid-template-columns': string|null;
    'grid-template-rows': string|null;
    'ime-mode': string|null;
    'justify-content': string|null;
    'justify-items': string|null;
    'justify-self': string|null;
    'layout-grid': string|null;
    'layout-grid-char': string|null;
    'layout-grid-line': string|null;
    'layout-grid-mode': string|null;
    'layout-grid-type': string|null;
    'readonlylength': number;
    'letter-spacing': string|null;
    'lighting-color': string|null;
    'line-break': string|null;
    'line-height': string|null;
    'list-style': string|null;
    'list-style-image': string|null;
    'list-style-position': string|null;
    'list-style-type': string|null;
    'margin-bottom': string|null;
    'margin-left': string|null;
    'margin-right': string|null;
    'margin-top': string|null;
    'marker-end': string|null;
    'marker-mid': string|null;
    'marker-start': string|null;
    'mask-image': string|null;
    'max-height': string|null;
    'max-width': string|null;
    'min-height': string|null;
    'min-width': string|null;
    'ms-content-zoom-chaining': string|null;
    'ms-content-zoom-limit': string|null;
    'ms-content-zoom-limit-max': any;
    'ms-content-zoom-limit-min': any;
    'ms-content-zoom-snap': string|null;
    'ms-content-zoom-snap-points': string|null;
    'ms-content-zoom-snap-type': string|null;
    'ms-content-zooming': string|null;
    'ms-flow-from': string|null;
    'ms-flow-into': string|null;
    'ms-font-feature-settings': string|null;
    'ms-grid-column': any;
    'ms-grid-column-align': string|null;
    'ms-grid-column-span': any;
    'ms-grid-columns': string|null;
    'ms-grid-row': any;
    'ms-grid-row-align': string|null;
    'ms-grid-row-span': any;
    'ms-grid-rows': string|null;
    'ms-high-contrast-adjust': string|null;
    'ms-hyphenate-limit-chars': string|null;
    'ms-hyphenate-limit-lines': any;
    'ms-hyphenate-limit-zone': any;
    'ms-hyphens': string|null;
    'ms-ime-align': string|null;
    'ms-overflow-style': string|null;
    'ms-scroll-chaining': string|null;
    'ms-scroll-limit': string|null;
    'ms-scroll-limit-x-max': any;
    'ms-scroll-limit-x-min': any;
    'ms-scroll-limit-y-max': any;
    'ms-scroll-limit-y-min': any;
    'ms-scroll-rails': string|null;
    'ms-scroll-snap-points-x': string|null;
    'ms-scroll-snap-points-y': string|null;
    'ms-scroll-snap-type': string|null;
    'ms-scroll-snap-x': string|null;
    'ms-scroll-snap-y': string|null;
    'ms-scroll-translation': string|null;
    'ms-text-combine-horizontal': string|null;
    'ms-text-size-adjust': any;
    'ms-touch-action': string|null;
    'ms-touch-select': string|null;
    'ms-user-select': string|null;
    'ms-wrap-flow': string;
    'ms-wrap-margin': any;
    'ms-wrap-through': string;
    'object-fit': string|null;
    'object-position': string|null;
    'outline-color': string|null;
    'outline-offset': string|null;
    'outline-style': string|null;
    'outline-width': string|null;
    'overflow-x': string|null;
    'overflow-y': string|null;
    'padding-bottom': string|null;
    'padding-left': string|null;
    'padding-right': string|null;
    'padding-top': string|null;
    'page-break-after': string|null;
    'page-break-before': string|null;
    'page-break-inside': string|null;
    'readonlyparent-rule': CSSRule;
    'pen-action': string|null;
    'perspective-origin': string|null;
    'pointer-events': string|null;
    'row-gap': string|null;
    'ruby-align': string|null;
    'ruby-overhang': string|null;
    'ruby-position': string|null;
    'scroll-behavior': string;
    'stop-color': string|null;
    'stop-opacity': string|null;
    'stroke-dasharray': string|null;
    'stroke-dashoffset': string|null;
    'stroke-linecap': string|null;
    'stroke-linejoin': string|null;
    'stroke-miterlimit': string|null;
    'stroke-opacity': string|null;
    'stroke-width': string|null;
    'table-layout': string|null;
    'text-align': string|null;
    'text-align-last': string|null;
    'text-anchor': string|null;
    'text-combine-upright': string|null;
    'text-decoration': string|null;
    'text-indent': string|null;
    'text-justify': string|null;
    'text-kashida': string|null;
    'text-kashida-space': string|null;
    'text-overflow': string|null;
    'text-shadow': string|null;
    'text-transform': string|null;
    'text-underline-position': string|null;
    'touch-action': string;
    'transform-origin': string|null;
    'transform-style': string|null;
    'transition-delay': string;
    'transition-duration': string;
    'transition-property': string;
    'transition-timing-function': string;
    'unicode-bidi': string|null;
    'user-select': string|null;
    'vertical-align': string|null;
    'webkit-align-content': string;
    'webkit-align-items': string;
    'webkit-align-self': string;
    'webkit-animation': string;
    'webkit-animation-delay': string;
    'webkit-animation-direction': string;
    'webkit-animation-duration': string;
    'webkit-animation-fill-mode': string;
    'webkit-animation-iteration-count': string;
    'webkit-animation-name': string;
    'webkit-animation-play-state': string;
    'webkit-animation-timing-function': string;
    'webkit-appearance': string;
    'webkit-backface-visibility': string;
    'webkit-background-clip': string;
    'webkit-background-origin': string;
    'webkit-background-size': string;
    'webkit-border-bottom-left-radius': string;
    'webkit-border-bottom-right-radius': string;
    'webkit-border-image': string|null;
    'webkit-border-radius': string;
    'webkit-border-top-left-radius': string;
    'webkit-border-top-right-radius': string;
    'webkit-box-align': string;
    'webkit-box-direction': string|null;
    'webkit-box-flex': string;
    'webkit-box-ordinal-group': string;
    'webkit-box-orient': string|null;
    'webkit-box-pack': string;
    'webkit-box-shadow': string;
    'webkit-box-sizing': string;
    'webkit-column-break-after': string|null;
    'webkit-column-break-before': string|null;
    'webkit-column-break-inside': string|null;
    'webkit-column-count': any;
    'webkit-column-gap': any;
    'webkit-column-rule': string|null;
    'webkit-column-rule-color': any;
    'webkit-column-rule-style': string|null;
    'webkit-column-rule-width': any;
    'webkit-column-span': string|null;
    'webkit-column-width': any;
    'webkit-columns': string|null;
    'webkit-filter': string;
    'webkit-flex': string;
    'webkit-flex-basis': string;
    'webkit-flex-direction': string;
    'webkit-flex-flow': string;
    'webkit-flex-grow': string;
    'webkit-flex-shrink': string;
    'webkit-flex-wrap': string;
    'webkit-justify-content': string;
    'webkit-mask': string;
    'webkit-mask-box-image': string;
    'webkit-mask-box-image-outset': string;
    'webkit-mask-box-image-repeat': string;
    'webkit-mask-box-image-slice': string;
    'webkit-mask-box-image-source': string;
    'webkit-mask-box-image-width': string;
    'webkit-mask-clip': string;
    'webkit-mask-composite': string;
    'webkit-mask-image': string;
    'webkit-mask-origin': string;
    'webkit-mask-position': string;
    'webkit-mask-repeat': string;
    'webkit-mask-size': string;
    'webkit-order': string;
    'webkit-perspective': string;
    'webkit-perspective-origin': string;
    'webkit-tap-highlight-color': string|null;
    'webkit-text-fill-color': string;
    'webkit-text-size-adjust': string;
    'webkit-text-stroke': string;
    'webkit-text-stroke-color': string;
    'webkit-text-stroke-width': string;
    'webkit-transform': string;
    'webkit-transform-origin': string;
    'webkit-transform-style': string;
    'webkit-transition': string;
    'webkit-transition-delay': string;
    'webkit-transition-duration': string;
    'webkit-transition-property': string;
    'webkit-transition-timing-function': string;
    'webkit-user-modify': string|null;
    'webkit-user-select': string|null;
    'webkit-writing-mode': string|null;
    'white-space': string|null;
    'word-break': string|null;
    'word-spacing': string|null;
    'word-wrap': string|null;
    'writing-mode': string|null;
    'z-index': string|null;
}