import {Merge, Partial} from "../../../lang";
import {VirtualElementAttributes} from "./TypedVirtualElementAttributes";
import {VirtualElementGlobalEventHandlers} from "./VirtualElementGlobalEventHandlers";

export interface HTMLVirtualElementAttributes extends VirtualElementAttributes, VirtualElementGlobalEventHandlers {
    class: string;
    className: string;
    style: string;
    classList: Array<string>;

    // TODO: Add all of them: MDN HTML Attribute reference!
    height: string|number;
    files: Array<string>;
    checked: string;
    defaultChecked: string;
    formNoValidate: string;
    indeterminate: string;
    maxLength: string;
    minLength: string;
    readOnly: string;
    selectionEnd: string;
    selectionStart: string;
    draggable: string;
    hidden: string;
    spellcheck: string;
    translate: string;
    msPlayToDisabled: string;
    msPlayToPrimary: string;
    noValidate: string;
    noShade: string;
    allowFullscreen: string;
    allowPaymentRequest: string;
    autoplay: string;
    controls: string;
    currentTime: string;
    defaultMuted: string;
    defaultPlaybackRate: string;
    loop: string;
    msRealTime: string;
    muted: string;
    playbackRate: string;
    srcObject: string;
    volume: string;
    high: string;
    low: string;
    min: string;
    optimum: string;
    compact: string;
    reversed: string;
    start: string;
    declare: string;
    hspace: string;
    typemustmatch: string;
    vspace: string;
    defaultSelected: string;
    selected: string;
    async: string;
    defer: string;
    noModule: string;
    colSpan: string;
    noWrap: string;
    rowSpan: string;
    span: string;
    caption: string;
    autofocus: string;
    cols: string;
    required: string;
    rows: string;
    default: string;
    msHorizontalMirror: string;
    msZoom: string;
    width: string;
    scrollRestoration: string;
}

declare global {
    namespace JSX {

        interface IntrinsicElements {
            "a": Merge<Partial<HTMLAnchorElement>, Partial<HTMLVirtualElementAttributes>>;
            "abbr": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "address": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "applet": Merge<Partial<HTMLAppletElement>, Partial<HTMLVirtualElementAttributes>>;
            "area": Merge<Partial<HTMLAreaElement>, Partial<HTMLVirtualElementAttributes>>;
            "article": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "aside": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "audio": Merge<Partial<HTMLAudioElement>, Partial<HTMLVirtualElementAttributes>>;
            "b": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "base": Merge<Partial<HTMLBaseElement>, Partial<HTMLVirtualElementAttributes>>;
            "basefont": Merge<Partial<HTMLBaseFontElement>, Partial<HTMLVirtualElementAttributes>>;
            "bdo": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "blockquote": Merge<Partial<HTMLQuoteElement>, Partial<HTMLVirtualElementAttributes>>;
            "body": Merge<Partial<HTMLBodyElement>, Partial<HTMLVirtualElementAttributes>>;
            "br": Merge<Partial<HTMLBRElement>, Partial<HTMLVirtualElementAttributes>>;
            "button": Merge<Partial<HTMLButtonElement>, Partial<HTMLVirtualElementAttributes>>;
            "canvas": Merge<Partial<HTMLCanvasElement>, Partial<HTMLVirtualElementAttributes>>;
            "caption": Merge<Partial<HTMLTableCaptionElement>, Partial<HTMLVirtualElementAttributes>>;
            "cite": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "code": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "col": Merge<Partial<HTMLTableColElement>, Partial<HTMLVirtualElementAttributes>>;
            "colgroup": Merge<Partial<HTMLTableColElement>, Partial<HTMLVirtualElementAttributes>>;
            "data": Merge<Partial<HTMLDataElement>, Partial<HTMLVirtualElementAttributes>>;
            "datalist": Merge<Partial<HTMLDataListElement>, Partial<HTMLVirtualElementAttributes>>;
            "dd": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "del": Merge<Partial<HTMLModElement>, Partial<HTMLVirtualElementAttributes>>;
            "details": Merge<Partial<HTMLDetailsElement>, Partial<HTMLVirtualElementAttributes>>;
            "dfn": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "dialog": Merge<Partial<HTMLDialogElement>, Partial<HTMLVirtualElementAttributes>>;
            "dir": Merge<Partial<HTMLDirectoryElement>, Partial<HTMLVirtualElementAttributes>>;
            "div": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "dl": Merge<Partial<HTMLDListElement>, Partial<HTMLVirtualElementAttributes>>;
            "dt": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "em": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "embed": Merge<Partial<HTMLEmbedElement>, Partial<HTMLVirtualElementAttributes>>;
            "fieldset": Merge<Partial<HTMLFieldSetElement>, Partial<HTMLVirtualElementAttributes>>;
            "figcaption": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "figure": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "font": Merge<Partial<HTMLFontElement>, Partial<HTMLVirtualElementAttributes>>;
            "footer": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "form": Merge<Partial<HTMLFormElement>, Partial<HTMLVirtualElementAttributes>>;
            "frame": Merge<Partial<HTMLFrameElement>, Partial<HTMLVirtualElementAttributes>>;
            "frameset": Merge<Partial<HTMLFrameSetElement>, Partial<HTMLVirtualElementAttributes>>;
            "h1": Merge<Partial<HTMLHeadingElement>, Partial<HTMLVirtualElementAttributes>>;
            "h2": Merge<Partial<HTMLHeadingElement>, Partial<HTMLVirtualElementAttributes>>;
            "h3": Merge<Partial<HTMLHeadingElement>, Partial<HTMLVirtualElementAttributes>>;
            "h4": Merge<Partial<HTMLHeadingElement>, Partial<HTMLVirtualElementAttributes>>;
            "h5": Merge<Partial<HTMLHeadingElement>, Partial<HTMLVirtualElementAttributes>>;
            "h6": Merge<Partial<HTMLHeadingElement>, Partial<HTMLVirtualElementAttributes>>;
            "head": Merge<Partial<HTMLHeadElement>, Partial<HTMLVirtualElementAttributes>>;
            "header": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "hgroup": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "hr": Merge<Partial<HTMLHRElement>, Partial<HTMLVirtualElementAttributes>>;
            "html": Merge<Partial<HTMLHtmlElement>, Partial<HTMLVirtualElementAttributes>>;
            "i": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "iframe": Merge<Partial<HTMLIFrameElement>, Partial<HTMLVirtualElementAttributes>>;
            "img": Merge<Partial<HTMLImageElement>, Partial<HTMLVirtualElementAttributes>>;
            "input": Merge<Partial<HTMLInputElement>, Partial<HTMLVirtualElementAttributes>>;
            "ins": Merge<Partial<HTMLModElement>, Partial<HTMLVirtualElementAttributes>>;
            "kbd": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "label": Merge<Partial<HTMLLabelElement>, Partial<HTMLVirtualElementAttributes>>;
            "legend": Merge<Partial<HTMLLegendElement>, Partial<HTMLVirtualElementAttributes>>;
            "li": Merge<Partial<HTMLLIElement>, Partial<HTMLVirtualElementAttributes>>;
            "link": Merge<Partial<HTMLLinkElement>, Partial<HTMLVirtualElementAttributes>>;
            "map": Merge<Partial<HTMLMapElement>, Partial<HTMLVirtualElementAttributes>>;
            "mark": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "marquee": Merge<Partial<HTMLMarqueeElement>, Partial<HTMLVirtualElementAttributes>>;
            "menu": Merge<Partial<HTMLMenuElement>, Partial<HTMLVirtualElementAttributes>>;
            "meta": Merge<Partial<HTMLMetaElement>, Partial<HTMLVirtualElementAttributes>>;
            "meter": Merge<Partial<HTMLMeterElement>, Partial<HTMLVirtualElementAttributes>>;
            "nav": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "noscript": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "object": Merge<Partial<HTMLObjectElement>, Partial<HTMLVirtualElementAttributes>>;
            "ol": Merge<Partial<HTMLOListElement>, Partial<HTMLVirtualElementAttributes>>;
            "optgroup": Merge<Partial<HTMLOptGroupElement>, Partial<HTMLVirtualElementAttributes>>;
            "option": Merge<Partial<HTMLOptionElement>, Partial<HTMLVirtualElementAttributes>>;
            "output": Merge<Partial<HTMLOutputElement>, Partial<HTMLVirtualElementAttributes>>;
            "p": Merge<Partial<HTMLParagraphElement>, Partial<HTMLVirtualElementAttributes>>;
            "param": Merge<Partial<HTMLParamElement>, Partial<HTMLVirtualElementAttributes>>;
            "picture": Merge<Partial<HTMLPictureElement>, Partial<HTMLVirtualElementAttributes>>;
            "pre": Merge<Partial<HTMLPreElement>, Partial<HTMLVirtualElementAttributes>>;
            "progress": Merge<Partial<HTMLProgressElement>, Partial<HTMLVirtualElementAttributes>>;
            "q": Merge<Partial<HTMLQuoteElement>, Partial<HTMLVirtualElementAttributes>>;
            "rt": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "ruby": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "s": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "samp": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "script": Merge<Partial<HTMLScriptElement>, Partial<HTMLVirtualElementAttributes>>;
            "section": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "select": Merge<Partial<HTMLSelectElement>, Partial<HTMLVirtualElementAttributes>>;
            "slot": Merge<Partial<HTMLSlotElement>, Partial<HTMLVirtualElementAttributes>>;
            "small": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "source": Merge<Partial<HTMLSourceElement>, Partial<HTMLVirtualElementAttributes>>;
            "span": Merge<Partial<HTMLSpanElement>, Partial<HTMLVirtualElementAttributes>>;
            "strong": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "style": Merge<Partial<HTMLStyleElement>, Partial<HTMLVirtualElementAttributes>>;
            "sub": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "sup": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "table": Merge<Partial<HTMLTableElement>, Partial<HTMLVirtualElementAttributes>>;
            "tbody": Merge<Partial<HTMLTableSectionElement>, Partial<HTMLVirtualElementAttributes>>;
            "td": Merge<Partial<HTMLTableDataCellElement>, Partial<HTMLVirtualElementAttributes>>;
            "template": Merge<Partial<HTMLTemplateElement>, Partial<HTMLVirtualElementAttributes>>;
            "textarea": Merge<Partial<HTMLTextAreaElement>, Partial<HTMLVirtualElementAttributes>>;
            "tfoot": Merge<Partial<HTMLTableSectionElement>, Partial<HTMLVirtualElementAttributes>>;
            "th": Merge<Partial<HTMLTableHeaderCellElement>, Partial<HTMLVirtualElementAttributes>>;
            "thead": Merge<Partial<HTMLTableSectionElement>, Partial<HTMLVirtualElementAttributes>>;
            "time": Merge<Partial<HTMLTimeElement>, Partial<HTMLVirtualElementAttributes>>;
            "title": Merge<Partial<HTMLTitleElement>, Partial<HTMLVirtualElementAttributes>>;
            "tr": Merge<Partial<HTMLTableRowElement>, Partial<HTMLVirtualElementAttributes>>;
            "track": Merge<Partial<HTMLTrackElement>, Partial<HTMLVirtualElementAttributes>>;
            "u": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "ul": Merge<Partial<HTMLUListElement>, Partial<HTMLVirtualElementAttributes>>;
            "var": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
            "video": Merge<Partial<HTMLVideoElement>, Partial<HTMLVirtualElementAttributes>>;
            "wbr": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;

            // fallback typing (catch-all tags not being typed, elements may lack type hinting on props then!)

            // @ts-ignore
            [tagName: string]: Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
        }
    }
}