import {Merge, Partial} from "../../../lang";
import {VirtualElementAttributes} from "./TypedVirtualElementAttributes";
import {VirtualElementGlobalEventHandlers} from "./VirtualElementGlobalEventHandlers";
import {SVGVirtualElementAttributes} from "./SVGIntrinsicElements";

export interface HTMLVirtualElementAttributes<T> extends VirtualElementAttributes, VirtualElementGlobalEventHandlers {
    class: string;
    className: string;
    style: string;
    classList: Array<string>;
    children: Array<T>;

    height: string|number|boolean;
    files: Array<string|number|boolean>;
    checked: string|number|boolean;
    defaultChecked: string|number|boolean;
    formNoValidate: string|number|boolean;
    indeterminate: string|number|boolean;
    maxLength: string|number|boolean;
    minLength: string|number|boolean;
    readOnly: string|number|boolean;
    selectionEnd: string|number|boolean;
    selectionStart: string|number|boolean;
    draggable: string|number|boolean;
    hidden: string|number|boolean;
    spellcheck: string|number|boolean;
    translate: string|number|boolean;
    msPlayToDisabled: string|number|boolean;
    msPlayToPrimary: string|number|boolean;
    noValidate: string|number|boolean;
    noShade: string|number|boolean;
    allowFullscreen: string|number|boolean;
    allowPaymentRequest: string|number|boolean;
    autoplay: string|number|boolean;
    controls: string|number|boolean;
    currentTime: string|number|boolean;
    defaultMuted: string|number|boolean;
    defaultPlaybackRate: string|number|boolean;
    loop: string|number|boolean;
    msRealTime: string|number|boolean;
    muted: string|number|boolean;
    playbackRate: string|number|boolean;
    srcObject: string|number|boolean;
    volume: string|number|boolean;
    high: string|number|boolean;
    low: string|number|boolean;
    min: string|number|boolean;
    optimum: string|number|boolean;
    compact: string|number|boolean;
    reversed: string|number|boolean;
    start: string|number|boolean;
    declare: string|number|boolean;
    hspace: string|number|boolean;
    typemustmatch: string|number|boolean;
    vspace: string|number|boolean;
    defaultSelected: string|number|boolean;
    selected: string|number|boolean;
    async: string|number|boolean;
    defer: string|number|boolean;
    noModule: string|number|boolean;
    colSpan: string|number|boolean;
    noWrap: string|number|boolean;
    rowSpan: string|number|boolean;
    span: string|number|boolean;
    caption: string|number|boolean;
    autofocus: string|number|boolean;
    cols: string|number|boolean;
    required: string|number|boolean;
    rows: string|number|boolean;
    default: string|number|boolean;
    msHorizontalMirror: string|number|boolean;
    msZoom: string|number|boolean;
    width: string|number|boolean;
    scrollRestoration: string|number|boolean;
    'accept': string|number|boolean;
    'accept-charset': string|number|boolean;
    'accesskey': string|number|boolean;
    'action': string|number|boolean;
    'align': string|number|boolean;
    'alt': string|number|boolean;
    'autocomplete': string|number|boolean;
    'autosave': string|number|boolean;
    'bgcolor': string|number|boolean;
    'border': string|number|boolean;
    'buffered': string|number|boolean;
    'challenge': string|number|boolean;
    'charset': string|number|boolean;
    'cite': string|number|boolean;
    'code': string|number|boolean;
    'codebase': string|number|boolean;
    'color': string|number|boolean;
    'colspan': string|number|boolean;
    'content': string|number|boolean;
    'contenteditable': string|number|boolean;
    'contextmenu': string|number|boolean;
    'coords': string|number|boolean;
    'crossorigin': string|number|boolean;
    'data': string|number|boolean;
    'datetime': string|number|boolean;
    'dir': string|number|boolean;
    'dirname': string|number|boolean;
    'disabled': string|number|boolean;
    'download': string|number|boolean;
    'dropzone': string|number|boolean;
    'enctype': string|number|boolean;
    'for': string|number|boolean;
    'form': string|number|boolean;
    'formaction': string|number|boolean;
    'headers': string|number|boolean;
    'href': string|number|boolean;
    'hreflang': string|number|boolean;
    'http-equiv': string|number|boolean;
    'icon': string|number|boolean;
    'id': string|number|boolean;
    'integrity': string|number|boolean;
    'ismap': string|number|boolean;
    'itemprop': string|number|boolean;
    'keytype': string|number|boolean;
    'kind': string|number|boolean;
    'label': string|number|boolean;
    'lang': string|number|boolean;
    'language': string|number|boolean;
    'list': string|number|boolean;
    'manifest': string|number|boolean;
    'max': string|number|boolean;
    'maxlength': string|number|boolean;
    'media': string|number|boolean;
    'method': string|number|boolean;
    'multiple': string|number|boolean;
    'name': string|number|boolean;
    'novalidate': string|number|boolean;
    'open': string|number|boolean;
    'pattern': string|number|boolean;
    'ping': string|number|boolean;
    'placeholder': string|number|boolean;
    'poster': string|number|boolean;
    'preload': string|number|boolean;
    'radiogroup': string|number|boolean;
    'readonly': string|number|boolean;
    'rel': string|number|boolean;
    'rowspan': string|number|boolean;
    'sandbox': string|number|boolean;
    'scope': string|number|boolean;
    'scoped': string|number|boolean;
    'seamless': string|number|boolean;
    'shape': string|number|boolean;
    'size': string|number|boolean;
    'text': string|number|boolean;
    'password': string|number|boolean;
    'sizes': string|number|boolean;
    'slot': string|number|boolean;
    'src': string|number|boolean;
    'srcdoc': string|number|boolean;
    'srclang': string|number|boolean;
    'srcset': string|number|boolean;
    'step': string|number|boolean;
    'summary': string|number|boolean;
    'tabindex': string|number|boolean;
    'target': string|number|boolean;
    'title': string|number|boolean;
    'usemap': string|number|boolean;
    'value': string|number|boolean;
    'wrap': string|number|boolean;
}

declare global {
    namespace JSX {

        interface IntrinsicElements {
            "a": Merge<Partial<SVGAElement>, Partial<SVGVirtualElementAttributes<SVGAElement>>> |
                 Merge<Partial<HTMLAnchorElement>, Partial<HTMLVirtualElementAttributes<HTMLAnchorElement>>>;
            "abbr": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "address": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "applet": Merge<Partial<HTMLAppletElement>, Partial<HTMLVirtualElementAttributes<HTMLAppletElement>>>;
            "area": Merge<Partial<HTMLAreaElement>, Partial<HTMLVirtualElementAttributes<HTMLAreaElement>>>;
            "article": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "aside": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "audio": Merge<Partial<HTMLAudioElement>, Partial<HTMLVirtualElementAttributes<HTMLAudioElement>>>;
            "b": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "base": Merge<Partial<HTMLBaseElement>, Partial<HTMLVirtualElementAttributes<HTMLBaseElement>>>;
            "basefont": Merge<Partial<HTMLBaseFontElement>, Partial<HTMLVirtualElementAttributes<HTMLBaseFontElement>>>;
            "bdo": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "blockquote": Merge<Partial<HTMLQuoteElement>, Partial<HTMLVirtualElementAttributes<HTMLQuoteElement>>>;
            "body": Merge<Partial<HTMLBodyElement>, Partial<HTMLVirtualElementAttributes<HTMLBodyElement>>>;
            "br": Merge<Partial<HTMLBRElement>, Partial<HTMLVirtualElementAttributes<HTMLBRElement>>>;
            "button": Merge<Partial<HTMLButtonElement>, Partial<HTMLVirtualElementAttributes<HTMLButtonElement>>>;
            "canvas": Merge<Partial<HTMLCanvasElement>, Partial<HTMLVirtualElementAttributes<HTMLCanvasElement>>>;
            "caption": Merge<Partial<HTMLTableCaptionElement>, Partial<HTMLVirtualElementAttributes<HTMLTableCaptionElement>>>;
            "cite": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "code": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "col": Merge<Partial<HTMLTableColElement>, Partial<HTMLVirtualElementAttributes<HTMLTableColElement>>>;
            "colgroup": Merge<Partial<HTMLTableColElement>, Partial<HTMLVirtualElementAttributes<HTMLTableColElement>>>;
            "data": Merge<Partial<HTMLDataElement>, Partial<HTMLVirtualElementAttributes<HTMLDataElement>>>;
            "datalist": Merge<Partial<HTMLDataListElement>, Partial<HTMLVirtualElementAttributes<HTMLDataListElement>>>;
            "dd": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "del": Merge<Partial<HTMLModElement>, Partial<HTMLVirtualElementAttributes<HTMLModElement>>>;
            "details": Merge<Partial<HTMLDetailsElement>, Partial<HTMLVirtualElementAttributes<HTMLDetailsElement>>>;
            "dfn": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "dialog": Merge<Partial<HTMLDialogElement>, Partial<HTMLVirtualElementAttributes<HTMLDialogElement>>>;
            "dir": Merge<Partial<HTMLDirectoryElement>, Partial<HTMLVirtualElementAttributes<HTMLDirectoryElement>>>;
            "div": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "dl": Merge<Partial<HTMLDListElement>, Partial<HTMLVirtualElementAttributes<HTMLDListElement>>>;
            "dt": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "em": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "embed": Merge<Partial<HTMLEmbedElement>, Partial<HTMLVirtualElementAttributes<HTMLEmbedElement>>>;
            "fieldset": Merge<Partial<HTMLFieldSetElement>, Partial<HTMLVirtualElementAttributes<HTMLFieldSetElement>>>;
            "figcaption": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "figure": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "font": Merge<Partial<HTMLFontElement>, Partial<HTMLVirtualElementAttributes<HTMLFontElement>>>;
            "footer": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "form": Merge<Partial<HTMLFormElement>, Partial<HTMLVirtualElementAttributes<HTMLFormElement>>>;
            "frame": Merge<Partial<HTMLFrameElement>, Partial<HTMLVirtualElementAttributes<HTMLFrameElement>>>;
            "frameset": Merge<Partial<HTMLFrameSetElement>, Partial<HTMLVirtualElementAttributes<HTMLFrameSetElement>>>;
            "h1": Merge<Partial<HTMLHeadingElement>, Partial<HTMLVirtualElementAttributes<HTMLHeadingElement>>>;
            "h2": Merge<Partial<HTMLHeadingElement>, Partial<HTMLVirtualElementAttributes<HTMLHeadingElement>>>;
            "h3": Merge<Partial<HTMLHeadingElement>, Partial<HTMLVirtualElementAttributes<HTMLHeadingElement>>>;
            "h4": Merge<Partial<HTMLHeadingElement>, Partial<HTMLVirtualElementAttributes<HTMLHeadingElement>>>;
            "h5": Merge<Partial<HTMLHeadingElement>, Partial<HTMLVirtualElementAttributes<HTMLHeadingElement>>>;
            "h6": Merge<Partial<HTMLHeadingElement>, Partial<HTMLVirtualElementAttributes<HTMLHeadingElement>>>;
            "head": Merge<Partial<HTMLHeadElement>, Partial<HTMLVirtualElementAttributes<HTMLHeadElement>>>;
            "header": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "hgroup": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "hr": Merge<Partial<HTMLHRElement>, Partial<HTMLVirtualElementAttributes<HTMLHRElement>>>;
            "html": Merge<Partial<HTMLHtmlElement>, Partial<HTMLVirtualElementAttributes<HTMLHtmlElement>>>;
            "i": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "iframe": Merge<Partial<HTMLIFrameElement>, Partial<HTMLVirtualElementAttributes<HTMLIFrameElement>>>;
            "img": Merge<Partial<HTMLImageElement>, Partial<HTMLVirtualElementAttributes<HTMLImageElement>>>;
            "input": Merge<Partial<HTMLInputElement>, Partial<HTMLVirtualElementAttributes<HTMLInputElement>>>;
            "ins": Merge<Partial<HTMLModElement>, Partial<HTMLVirtualElementAttributes<HTMLModElement>>>;
            "kbd": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "label": Merge<Partial<HTMLLabelElement>, Partial<HTMLVirtualElementAttributes<HTMLLabelElement>>>;
            "legend": Merge<Partial<HTMLLegendElement>, Partial<HTMLVirtualElementAttributes<HTMLLegendElement>>>;
            "li": Merge<Partial<HTMLLIElement>, Partial<HTMLVirtualElementAttributes<HTMLLIElement>>>;
            "link": Merge<Partial<HTMLLinkElement>, Partial<HTMLVirtualElementAttributes<HTMLLinkElement>>>;
            "map": Merge<Partial<HTMLMapElement>, Partial<HTMLVirtualElementAttributes<HTMLMapElement>>>;
            "mark": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "marquee": Merge<Partial<HTMLMarqueeElement>, Partial<HTMLVirtualElementAttributes<HTMLMarqueeElement>>>;
            "menu": Merge<Partial<HTMLMenuElement>, Partial<HTMLVirtualElementAttributes<HTMLMenuElement>>>;
            "meta": Merge<Partial<HTMLMetaElement>, Partial<HTMLVirtualElementAttributes<HTMLMetaElement>>>;
            "meter": Merge<Partial<HTMLMeterElement>, Partial<HTMLVirtualElementAttributes<HTMLMeterElement>>>;
            "nav": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "noscript": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "object": Merge<Partial<HTMLObjectElement>, Partial<HTMLVirtualElementAttributes<HTMLObjectElement>>>;
            "ol": Merge<Partial<HTMLOListElement>, Partial<HTMLVirtualElementAttributes<HTMLOListElement>>>;
            "optgroup": Merge<Partial<HTMLOptGroupElement>, Partial<HTMLVirtualElementAttributes<HTMLOptGroupElement>>>;
            "option": Merge<Partial<HTMLOptionElement>, Partial<HTMLVirtualElementAttributes<HTMLOptionElement>>>;
            "output": Merge<Partial<HTMLOutputElement>, Partial<HTMLVirtualElementAttributes<HTMLOutputElement>>>;
            "p": Merge<Partial<HTMLParagraphElement>, Partial<HTMLVirtualElementAttributes<HTMLParagraphElement>>>;
            "param": Merge<Partial<HTMLParamElement>, Partial<HTMLVirtualElementAttributes<HTMLParamElement>>>;
            "picture": Merge<Partial<HTMLPictureElement>, Partial<HTMLVirtualElementAttributes<HTMLPictureElement>>>;
            "pre": Merge<Partial<HTMLPreElement>, Partial<HTMLVirtualElementAttributes<HTMLPreElement>>>;
            "progress": Merge<Partial<HTMLProgressElement>, Partial<HTMLVirtualElementAttributes<HTMLProgressElement>>>;
            "q": Merge<Partial<HTMLQuoteElement>, Partial<HTMLVirtualElementAttributes<HTMLQuoteElement>>>;
            "rt": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "ruby": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "s": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "samp": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "script": Merge<Partial<HTMLScriptElement>, Partial<HTMLVirtualElementAttributes<HTMLScriptElement>>> |
                Merge<Partial<SVGScriptElement>, Partial<SVGVirtualElementAttributes<SVGScriptElement>>>;
            "section": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "select": Merge<Partial<HTMLSelectElement>, Partial<HTMLVirtualElementAttributes<HTMLSelectElement>>>;
            "slot": Merge<Partial<HTMLSlotElement>, Partial<HTMLVirtualElementAttributes<HTMLSlotElement>>>;
            "small": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "source": Merge<Partial<HTMLSourceElement>, Partial<HTMLVirtualElementAttributes<HTMLSourceElement>>>;
            "span": Merge<Partial<HTMLSpanElement>, Partial<HTMLVirtualElementAttributes<HTMLSpanElement>>>;
            "strong": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "style": Merge<Partial<HTMLStyleElement>, Partial<HTMLVirtualElementAttributes<HTMLStyleElement>>> |
                Merge<Partial<SVGStyleElement>, Partial<SVGVirtualElementAttributes<SVGStyleElement>>>;
            "sub": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "sup": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "table": Merge<Partial<HTMLTableElement>, Partial<HTMLVirtualElementAttributes<HTMLTableElement>>>;
            "tbody": Merge<Partial<HTMLTableSectionElement>, Partial<HTMLVirtualElementAttributes<HTMLTableSectionElement>>>;
            "td": Merge<Partial<HTMLTableDataCellElement>, Partial<HTMLVirtualElementAttributes<HTMLTableDataCellElement>>>;
            "template": Merge<Partial<HTMLTemplateElement>, Partial<HTMLVirtualElementAttributes<HTMLTemplateElement>>>;
            "textarea": Merge<Partial<HTMLTextAreaElement>, Partial<HTMLVirtualElementAttributes<HTMLTextAreaElement>>>;
            "tfoot": Merge<Partial<HTMLTableSectionElement>, Partial<HTMLVirtualElementAttributes<HTMLTableSectionElement>>>;
            "th": Merge<Partial<HTMLTableHeaderCellElement>, Partial<HTMLVirtualElementAttributes<HTMLTableHeaderCellElement>>>;
            "thead": Merge<Partial<HTMLTableSectionElement>, Partial<HTMLVirtualElementAttributes<HTMLTableSectionElement>>>;
            "time": Merge<Partial<HTMLTimeElement>, Partial<HTMLVirtualElementAttributes<HTMLTimeElement>>>;
            "title": Merge<Partial<SVGTitleElement>, Partial<SVGVirtualElementAttributes<SVGTitleElement>>> |
                     Merge<Partial<HTMLTitleElement>, Partial<HTMLVirtualElementAttributes<HTMLTitleElement>>>;
            "tr": Merge<Partial<HTMLTableRowElement>, Partial<HTMLVirtualElementAttributes<HTMLTableRowElement>>>;
            "track": Merge<Partial<HTMLTrackElement>, Partial<HTMLVirtualElementAttributes<HTMLTrackElement>>>;
            "u": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "ul": Merge<Partial<HTMLUListElement>, Partial<HTMLVirtualElementAttributes<HTMLUListElement>>>;
            "var": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;
            "video": Merge<Partial<HTMLVideoElement>, Partial<HTMLVirtualElementAttributes<HTMLVideoElement>>>;
            "wbr": Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes<HTMLElement>>>;

            // fallback typing (catch-all tags not being typed, elements may lack type hinting on props then!)

            // @ts-ignore
            [tagName: string]: Merge<Partial<HTMLElement>, Partial<HTMLVirtualElementAttributes>>;
        }
    }
}