export interface ITypedCSSStyleDeclaration {
    alignContent: number | string | null | Array<number | string | null>;
    alignItems: number | string | null | Array<number | string | null>;
    alignSelf: number | string | null | Array<number | string | null>;
    alignmentBaseline: number | string | null | Array<number | string | null>;
    animation: string | Array<number | string | null>;
    animationDelay: string | Array<number | string | null>;
    animationDirection: string | Array<number | string | null>;
    animationDuration: string | Array<number | string | null>;
    animationFillMode: string | Array<number | string | null>;
    animationIterationCount: string | Array<number | string | null>;
    animationName: string | Array<number | string | null>;
    animationPlayState: string | Array<number | string | null>;
    animationTimingFunction: string | Array<number | string | null>;
    backfaceVisibility: number | string | null | Array<number | string | null>;
    background: number | string | null | Array<number | string | null>;
    backgroundAttachment: number | string | null | Array<number | string | null>;
    backgroundClip: number | string | null | Array<number | string | null>;
    backgroundColor: number | string | null | Array<number | string | null>;
    backgroundImage: number | string | null | Array<number | string | null>;
    backgroundOrigin: number | string | null | Array<number | string | null>;
    backgroundPosition: number | string | null | Array<number | string | null>;
    backgroundPositionX: number | string | null | Array<number | string | null>;
    backgroundPositionY: number | string | null | Array<number | string | null>;
    backgroundRepeat: number | string | null | Array<number | string | null>;
    backgroundSize: number | string | null | Array<number | string | null>;
    baselineShift: number | string | null | Array<number | string | null>;
    border: number | string | null | Array<number | string | null>;
    borderBottom: number | string | null | Array<number | string | null>;
    borderBottomColor: number | string | null | Array<number | string | null>;
    borderBottomLeftRadius: number | string | null | Array<number | string | null>;
    borderBottomRightRadius: number | string | null | Array<number | string | null>;
    borderBottomStyle: number | string | null | Array<number | string | null>;
    borderBottomWidth: number | string | null | Array<number | string | null>;
    borderCollapse: number | string | null | Array<number | string | null>;
    borderColor: number | string | null | Array<number | string | null>;
    borderImage: number | string | null | Array<number | string | null>;
    borderImageOutset: number | string | null | Array<number | string | null>;
    borderImageRepeat: number | string | null | Array<number | string | null>;
    borderImageSlice: number | string | null | Array<number | string | null>;
    borderImageSource: number | string | null | Array<number | string | null>;
    borderImageWidth: number | string | null | Array<number | string | null>;
    borderLeft: number | string | null | Array<number | string | null>;
    borderLeftColor: number | string | null | Array<number | string | null>;
    borderLeftStyle: number | string | null | Array<number | string | null>;
    borderLeftWidth: number | string | null | Array<number | string | null>;
    borderRadius: number | string | null | Array<number | string | null>;
    borderRight: number | string | null | Array<number | string | null>;
    borderRightColor: number | string | null | Array<number | string | null>;
    borderRightStyle: number | string | null | Array<number | string | null>;
    borderRightWidth: number | string | null | Array<number | string | null>;
    borderSpacing: number | string | null | Array<number | string | null>;
    borderStyle: number | string | null | Array<number | string | null>;
    borderTop: number | string | null | Array<number | string | null>;
    borderTopColor: number | string | null | Array<number | string | null>;
    borderTopLeftRadius: number | string | null | Array<number | string | null>;
    borderTopRightRadius: number | string | null | Array<number | string | null>;
    borderTopStyle: number | string | null | Array<number | string | null>;
    borderTopWidth: number | string | null | Array<number | string | null>;
    borderWidth: number | string | null | Array<number | string | null>;
    bottom: number | string | null | Array<number | string | null>;
    boxShadow: number | string | null | Array<number | string | null>;
    boxSizing: number | string | null | Array<number | string | null>;
    breakAfter: number | string | null | Array<number | string | null>;
    breakBefore: number | string | null | Array<number | string | null>;
    breakInside: number | string | null | Array<number | string | null>;
    captionSide: number | string | null | Array<number | string | null>;
    clear: number | string | null | Array<number | string | null>;
    clip: number | string | null | Array<number | string | null>;
    clipPath: number | string | null | Array<number | string | null>;
    clipRule: number | string | null | Array<number | string | null>;
    color: number | string | null | Array<number | string | null>;
    colorInterpolationFilters: number | string | null | Array<number | string | null>;
    columnCount: any | Array<number | string | null>;
    columnFill: number | string | null | Array<number | string | null>;
    columnGap: any | Array<number | string | null>;
    columnRule: number | string | null | Array<number | string | null>;
    columnRuleColor: any | Array<number | string | null>;
    columnRuleStyle: number | string | null | Array<number | string | null>;
    columnRuleWidth: any | Array<number | string | null>;
    columnSpan: number | string | null | Array<number | string | null>;
    columnWidth: any | Array<number | string | null>;
    columns: number | string | null | Array<number | string | null>;
    content: number | string | null | Array<number | string | null>;
    counterIncrement: number | string | null | Array<number | string | null>;
    counterReset: number | string | null | Array<number | string | null>;
    cssFloat: number | string | null | Array<number | string | null>;
    cssText: string | Array<number | string | null>;
    cursor: number | string | null | Array<number | string | null>;
    direction: number | string | null | Array<number | string | null>;
    display: number | string | null | Array<number | string | null>;
    dominantBaseline: number | string | null | Array<number | string | null>;
    emptyCells: number | string | null | Array<number | string | null>;
    enableBackground: number | string | null | Array<number | string | null>;
    fill: number | string | null | Array<number | string | null>;
    fillOpacity: number | string | null | Array<number | string | null>;
    fillRule: number | string | null | Array<number | string | null>;
    filter: number | string | null | Array<number | string | null>;
    flex: number | string | null | Array<number | string | null>;
    flexBasis: number | string | null | Array<number | string | null>;
    flexDirection: number | string | null | Array<number | string | null>;
    flexFlow: number | string | null | Array<number | string | null>;
    flexGrow: number | string | null | Array<number | string | null>;
    flexShrink: number | string | null | Array<number | string | null>;
    flexWrap: number | string | null | Array<number | string | null>;
    floodColor: number | string | null | Array<number | string | null>;
    floodOpacity: number | string | null | Array<number | string | null>;
    font: number | string | null | Array<number | string | null>;
    fontFamily: number | string | null | Array<number | string | null>;
    fontFeatureSettings: number | string | null | Array<number | string | null>;
    fontSize: number | string | null | Array<number | string | null>;
    fontSizeAdjust: number | string | null | Array<number | string | null>;
    fontStretch: number | string | null | Array<number | string | null>;
    fontStyle: number | string | null | Array<number | string | null>;
    fontVariant: number | string | null | Array<number | string | null>;
    fontWeight: number | string | null | Array<number | string | null>;
    gap: number | string | null | Array<number | string | null>;
    glyphOrientationHorizontal: number | string | null | Array<number | string | null>;
    glyphOrientationVertical: number | string | null | Array<number | string | null>;
    grid: number | string | null | Array<number | string | null>;
    gridArea: number | string | null | Array<number | string | null>;
    gridAutoColumns: number | string | null | Array<number | string | null>;
    gridAutoFlow: number | string | null | Array<number | string | null>;
    gridAutoRows: number | string | null | Array<number | string | null>;
    gridColumn: number | string | null | Array<number | string | null>;
    gridColumnEnd: number | string | null | Array<number | string | null>;
    gridColumnGap: number | string | null | Array<number | string | null>;
    gridColumnStart: number | string | null | Array<number | string | null>;
    gridGap: number | string | null | Array<number | string | null>;
    gridRow: number | string | null | Array<number | string | null>;
    gridRowEnd: number | string | null | Array<number | string | null>;
    gridRowGap: number | string | null | Array<number | string | null>;
    gridRowStart: number | string | null | Array<number | string | null>;
    gridTemplate: number | string | null | Array<number | string | null>;
    gridTemplateAreas: number | string | null | Array<number | string | null>;
    gridTemplateColumns: number | string | null | Array<number | string | null>;
    gridTemplateRows: number | string | null | Array<number | string | null>;
    height: number | string | null | Array<number | string | null>;
    imeMode: number | string | null | Array<number | string | null>;
    justifyContent: number | string | null | Array<number | string | null>;
    justifyItems: number | string | null | Array<number | string | null>;
    justifySelf: number | string | null | Array<number | string | null>;
    kerning: number | string | null | Array<number | string | null>;
    layoutGrid: number | string | null | Array<number | string | null>;
    layoutGridChar: number | string | null | Array<number | string | null>;
    layoutGridLine: number | string | null | Array<number | string | null>;
    layoutGridMode: number | string | null | Array<number | string | null>;
    layoutGridType: number | string | null | Array<number | string | null>;
    left: number | string | null | Array<number | string | null>;
    readonly length: number | Array<number | string | null>;
    letterSpacing: number | string | null | Array<number | string | null>;
    lightingColor: number | string | null | Array<number | string | null>;
    lineBreak: number | string | null | Array<number | string | null>;
    lineHeight: number | string | null | Array<number | string | null>;
    listStyle: number | string | null | Array<number | string | null>;
    listStyleImage: number | string | null | Array<number | string | null>;
    listStylePosition: number | string | null | Array<number | string | null>;
    listStyleType: number | string | null | Array<number | string | null>;
    margin: number | string | null | Array<number | string | null>;
    marginBottom: number | string | null | Array<number | string | null>;
    marginLeft: number | string | null | Array<number | string | null>;
    marginRight: number | string | null | Array<number | string | null>;
    marginTop: number | string | null | Array<number | string | null>;
    marker: number | string | null | Array<number | string | null>;
    markerEnd: number | string | null | Array<number | string | null>;
    markerMid: number | string | null | Array<number | string | null>;
    markerStart: number | string | null | Array<number | string | null>;
    mask: number | string | null | Array<number | string | null>;
    maskImage: number | string | null | Array<number | string | null>;
    maxHeight: number | string | null | Array<number | string | null>;
    maxWidth: number | string | null | Array<number | string | null>;
    minHeight: number | string | null | Array<number | string | null>;
    minWidth: number | string | null | Array<number | string | null>;
    msContentZoomChaining: number | string | null | Array<number | string | null>;
    msContentZoomLimit: number | string | null | Array<number | string | null>;
    msContentZoomLimitMax: any | Array<number | string | null>;
    msContentZoomLimitMin: any | Array<number | string | null>;
    msContentZoomSnap: number | string | null | Array<number | string | null>;
    msContentZoomSnapPoints: number | string | null | Array<number | string | null>;
    msContentZoomSnapType: number | string | null | Array<number | string | null>;
    msContentZooming: number | string | null | Array<number | string | null>;
    msFlowFrom: number | string | null | Array<number | string | null>;
    msFlowInto: number | string | null | Array<number | string | null>;
    msFontFeatureSettings: number | string | null | Array<number | string | null>;
    msGridColumn: any | Array<number | string | null>;
    msGridColumnAlign: number | string | null | Array<number | string | null>;
    msGridColumnSpan: any | Array<number | string | null>;
    msGridColumns: number | string | null | Array<number | string | null>;
    msGridRow: any | Array<number | string | null>;
    msGridRowAlign: number | string | null | Array<number | string | null>;
    msGridRowSpan: any | Array<number | string | null>;
    msGridRows: number | string | null | Array<number | string | null>;
    msHighContrastAdjust: number | string | null | Array<number | string | null>;
    msHyphenateLimitChars: number | string | null | Array<number | string | null>;
    msHyphenateLimitLines: any | Array<number | string | null>;
    msHyphenateLimitZone: any | Array<number | string | null>;
    msHyphens: number | string | null | Array<number | string | null>;
    msImeAlign: number | string | null | Array<number | string | null>;
    msOverflowStyle: number | string | null | Array<number | string | null>;
    msScrollChaining: number | string | null | Array<number | string | null>;
    msScrollLimit: number | string | null | Array<number | string | null>;
    msScrollLimitXMax: any | Array<number | string | null>;
    msScrollLimitXMin: any | Array<number | string | null>;
    msScrollLimitYMax: any | Array<number | string | null>;
    msScrollLimitYMin: any | Array<number | string | null>;
    msScrollRails: number | string | null | Array<number | string | null>;
    msScrollSnapPointsX: number | string | null | Array<number | string | null>;
    msScrollSnapPointsY: number | string | null | Array<number | string | null>;
    msScrollSnapType: number | string | null | Array<number | string | null>;
    msScrollSnapX: number | string | null | Array<number | string | null>;
    msScrollSnapY: number | string | null | Array<number | string | null>;
    msScrollTranslation: number | string | null | Array<number | string | null>;
    msTextCombineHorizontal: number | string | null | Array<number | string | null>;
    msTextSizeAdjust: any | Array<number | string | null>;
    msTouchAction: number | string | null | Array<number | string | null>;
    msTouchSelect: number | string | null | Array<number | string | null>;
    msUserSelect: number | string | null | Array<number | string | null>;
    msWrapFlow: string | Array<number | string | null>;
    msWrapMargin: any | Array<number | string | null>;
    msWrapThrough: string | Array<number | string | null>;
    objectFit: number | string | null | Array<number | string | null>;
    objectPosition: number | string | null | Array<number | string | null>;
    opacity: number | string | null | Array<number | string | null>;
    order: number | string | null | Array<number | string | null>;
    orphans: number | string | null | Array<number | string | null>;
    outline: number | string | null | Array<number | string | null>;
    outlineColor: number | string | null | Array<number | string | null>;
    outlineOffset: number | string | null | Array<number | string | null>;
    outlineStyle: number | string | null | Array<number | string | null>;
    outlineWidth: number | string | null | Array<number | string | null>;
    overflow: number | string | null | Array<number | string | null>;
    overflowX: number | string | null | Array<number | string | null>;
    overflowY: number | string | null | Array<number | string | null>;
    padding: number | string | null | Array<number | string | null>;
    paddingBottom: number | string | null | Array<number | string | null>;
    paddingLeft: number | string | null | Array<number | string | null>;
    paddingRight: number | string | null | Array<number | string | null>;
    paddingTop: number | string | null | Array<number | string | null>;
    pageBreakAfter: number | string | null | Array<number | string | null>;
    pageBreakBefore: number | string | null | Array<number | string | null>;
    pageBreakInside: number | string | null | Array<number | string | null>;
    readonly parentRule: CSSRule | Array<number | string | null>;
    penAction: number | string | null | Array<number | string | null>;
    perspective: number | string | null | Array<number | string | null>;
    perspectiveOrigin: number | string | null | Array<number | string | null>;
    pointerEvents: number | string | null | Array<number | string | null>;
    position: number | string | null | Array<number | string | null>;
    quotes: number | string | null | Array<number | string | null>;
    resize: number | string | null | Array<number | string | null>;
    right: number | string | null | Array<number | string | null>;
    rotate: number | string | null | Array<number | string | null>;
    rowGap: number | string | null | Array<number | string | null>;
    rubyAlign: number | string | null | Array<number | string | null>;
    rubyOverhang: number | string | null | Array<number | string | null>;
    rubyPosition: number | string | null | Array<number | string | null>;
    scale: number | string | null | Array<number | string | null>;
    scrollBehavior: string | Array<number | string | null>;
    stopColor: number | string | null | Array<number | string | null>;
    stopOpacity: number | string | null | Array<number | string | null>;
    stroke: number | string | null | Array<number | string | null>;
    strokeDasharray: number | string | null | Array<number | string | null>;
    strokeDashoffset: number | string | null | Array<number | string | null>;
    strokeLinecap: number | string | null | Array<number | string | null>;
    strokeLinejoin: number | string | null | Array<number | string | null>;
    strokeMiterlimit: number | string | null | Array<number | string | null>;
    strokeOpacity: number | string | null | Array<number | string | null>;
    strokeWidth: number | string | null | Array<number | string | null>;
    tableLayout: number | string | null | Array<number | string | null>;
    textAlign: number | string | null | Array<number | string | null>;
    textAlignLast: number | string | null | Array<number | string | null>;
    textAnchor: number | string | null | Array<number | string | null>;
    textCombineUpright: number | string | null | Array<number | string | null>;
    textDecoration: number | string | null | Array<number | string | null>;
    textIndent: number | string | null | Array<number | string | null>;
    textJustify: number | string | null | Array<number | string | null>;
    textKashida: number | string | null | Array<number | string | null>;
    textKashidaSpace: number | string | null | Array<number | string | null>;
    textOverflow: number | string | null | Array<number | string | null>;
    textShadow: number | string | null | Array<number | string | null>;
    textTransform: number | string | null | Array<number | string | null>;
    textUnderlinePosition: number | string | null | Array<number | string | null>;
    top: number | string | null | Array<number | string | null>;
    touchAction: string | Array<number | string | null>;
    transform: number | string | null | Array<number | string | null>;
    transformOrigin: number | string | null | Array<number | string | null>;
    transformStyle: number | string | null | Array<number | string | null>;
    transition: string | Array<number | string | null>;
    transitionDelay: string | Array<number | string | null>;
    transitionDuration: string | Array<number | string | null>;
    transitionProperty: string | Array<number | string | null>;
    transitionTimingFunction: string | Array<number | string | null>;
    translate: number | string | null | Array<number | string | null>;
    unicodeBidi: number | string | null | Array<number | string | null>;
    userSelect: number | string | null | Array<number | string | null>;
    verticalAlign: number | string | null | Array<number | string | null>;
    visibility: number | string | null | Array<number | string | null>;
    /** @deprecated */
    webkitAlignContent: string | Array<number | string | null>;
    /** @deprecated */
    webkitAlignItems: string | Array<number | string | null>;
    /** @deprecated */
    webkitAlignSelf: string | Array<number | string | null>;
    /** @deprecated */
    webkitAnimation: string | Array<number | string | null>;
    /** @deprecated */
    webkitAnimationDelay: string | Array<number | string | null>;
    /** @deprecated */
    webkitAnimationDirection: string | Array<number | string | null>;
    /** @deprecated */
    webkitAnimationDuration: string | Array<number | string | null>;
    /** @deprecated */
    webkitAnimationFillMode: string | Array<number | string | null>;
    /** @deprecated */
    webkitAnimationIterationCount: string | Array<number | string | null>;
    /** @deprecated */
    webkitAnimationName: string | Array<number | string | null>;
    /** @deprecated */
    webkitAnimationPlayState: string | Array<number | string | null>;
    /** @deprecated */
    webkitAnimationTimingFunction: string | Array<number | string | null>;
    /** @deprecated */
    webkitAppearance: string | Array<number | string | null>;
    /** @deprecated */
    webkitBackfaceVisibility: string | Array<number | string | null>;
    /** @deprecated */
    webkitBackgroundClip: string | Array<number | string | null>;
    /** @deprecated */
    webkitBackgroundOrigin: string | Array<number | string | null>;
    /** @deprecated */
    webkitBackgroundSize: string | Array<number | string | null>;
    /** @deprecated */
    webkitBorderBottomLeftRadius: string | Array<number | string | null>;
    /** @deprecated */
    webkitBorderBottomRightRadius: string | Array<number | string | null>;
    webkitBorderImage: number | string | null | Array<number | string | null>;
    /** @deprecated */
    webkitBorderRadius: string | Array<number | string | null>;
    /** @deprecated */
    webkitBorderTopLeftRadius: string | Array<number | string | null>;
    /** @deprecated */
    webkitBorderTopRightRadius: string | Array<number | string | null>;
    /** @deprecated */
    webkitBoxAlign: string | Array<number | string | null>;
    webkitBoxDirection: number | string | null | Array<number | string | null>;
    /** @deprecated */
    webkitBoxFlex: string | Array<number | string | null>;
    /** @deprecated */
    webkitBoxOrdinalGroup: string | Array<number | string | null>;
    webkitBoxOrient: number | string | null | Array<number | string | null>;
    /** @deprecated */
    webkitBoxPack: string | Array<number | string | null>;
    /** @deprecated */
    webkitBoxShadow: string | Array<number | string | null>;
    /** @deprecated */
    webkitBoxSizing: string | Array<number | string | null>;
    webkitColumnBreakAfter: number | string | null | Array<number | string | null>;
    webkitColumnBreakBefore: number | string | null | Array<number | string | null>;
    webkitColumnBreakInside: number | string | null | Array<number | string | null>;
    webkitColumnCount: any | Array<number | string | null>;
    webkitColumnGap: any | Array<number | string | null>;
    webkitColumnRule: number | string | null | Array<number | string | null>;
    webkitColumnRuleColor: any | Array<number | string | null>;
    webkitColumnRuleStyle: number | string | null | Array<number | string | null>;
    webkitColumnRuleWidth: any | Array<number | string | null>;
    webkitColumnSpan: number | string | null | Array<number | string | null>;
    webkitColumnWidth: any | Array<number | string | null>;
    webkitColumns: number | string | null | Array<number | string | null>;
    /** @deprecated */
    webkitFilter: string | Array<number | string | null>;
    /** @deprecated */
    webkitFlex: string | Array<number | string | null>;
    /** @deprecated */
    webkitFlexBasis: string | Array<number | string | null>;
    /** @deprecated */
    webkitFlexDirection: string | Array<number | string | null>;
    /** @deprecated */
    webkitFlexFlow: string | Array<number | string | null>;
    /** @deprecated */
    webkitFlexGrow: string | Array<number | string | null>;
    /** @deprecated */
    webkitFlexShrink: string | Array<number | string | null>;
    /** @deprecated */
    webkitFlexWrap: string | Array<number | string | null>;
    /** @deprecated */
    webkitJustifyContent: string | Array<number | string | null>;
    /** @deprecated */
    webkitMask: string | Array<number | string | null>;
    /** @deprecated */
    webkitMaskBoxImage: string | Array<number | string | null>;
    /** @deprecated */
    webkitMaskBoxImageOutset: string | Array<number | string | null>;
    /** @deprecated */
    webkitMaskBoxImageRepeat: string | Array<number | string | null>;
    /** @deprecated */
    webkitMaskBoxImageSlice: string | Array<number | string | null>;
    /** @deprecated */
    webkitMaskBoxImageSource: string | Array<number | string | null>;
    /** @deprecated */
    webkitMaskBoxImageWidth: string | Array<number | string | null>;
    /** @deprecated */
    webkitMaskClip: string | Array<number | string | null>;
    /** @deprecated */
    webkitMaskComposite: string | Array<number | string | null>;
    /** @deprecated */
    webkitMaskImage: string | Array<number | string | null>;
    /** @deprecated */
    webkitMaskOrigin: string | Array<number | string | null>;
    /** @deprecated */
    webkitMaskPosition: string | Array<number | string | null>;
    /** @deprecated */
    webkitMaskRepeat: string | Array<number | string | null>;
    /** @deprecated */
    webkitMaskSize: string | Array<number | string | null>;
    /** @deprecated */
    webkitOrder: string | Array<number | string | null>;
    /** @deprecated */
    webkitPerspective: string | Array<number | string | null>;
    /** @deprecated */
    webkitPerspectiveOrigin: string | Array<number | string | null>;
    webkitTapHighlightColor: number | string | null | Array<number | string | null>;
    /** @deprecated */
    webkitTextFillColor: string | Array<number | string | null>;
    /** @deprecated */
    webkitTextSizeAdjust: string | Array<number | string | null>;
    /** @deprecated */
    webkitTextStroke: string | Array<number | string | null>;
    /** @deprecated */
    webkitTextStrokeColor: string | Array<number | string | null>;
    /** @deprecated */
    webkitTextStrokeWidth: string | Array<number | string | null>;
    /** @deprecated */
    webkitTransform: string | Array<number | string | null>;
    /** @deprecated */
    webkitTransformOrigin: string | Array<number | string | null>;
    /** @deprecated */
    webkitTransformStyle: string | Array<number | string | null>;
    /** @deprecated */
    webkitTransition: string | Array<number | string | null>;
    /** @deprecated */
    webkitTransitionDelay: string | Array<number | string | null>;
    /** @deprecated */
    webkitTransitionDuration: string | Array<number | string | null>;
    /** @deprecated */
    webkitTransitionProperty: string | Array<number | string | null>;
    /** @deprecated */
    webkitTransitionTimingFunction: string | Array<number | string | null>;
    webkitUserModify: number | string | null | Array<number | string | null>;
    webkitUserSelect: number | string | null | Array<number | string | null>;
    webkitWritingMode: number | string | null | Array<number | string | null>;
    whiteSpace: number | string | null | Array<number | string | null>;
    widows: number | string | null | Array<number | string | null>;
    width: number | string | null | Array<number | string | null>;
    wordBreak: number | string | null | Array<number | string | null>;
    wordSpacing: number | string | null | Array<number | string | null>;
    wordWrap: number | string | null | Array<number | string | null>;
    writingMode: number | string | null | Array<number | string | null>;
    zIndex: number | string | null | Array<number | string | null>;
    zoom: number | string | null | Array<number | string | null>;

    // traditional style
    'align-content': string|null | Array<number | string | null>;
    'align-items': string|null | Array<number | string | null>;
    'align-self': string|null | Array<number | string | null>;
    'alignment-baseline': string|null | Array<number | string | null>;
    'animation-delay': string | Array<number | string | null>;
    'animation-direction': string | Array<number | string | null>;
    'animation-duration': string | Array<number | string | null>;
    'animation-fill-mode': string | Array<number | string | null>;
    'animation-iteration-count': string | Array<number | string | null>;
    'animation-name': string | Array<number | string | null>;
    'animation-play-state': string | Array<number | string | null>;
    'animation-timing-function': string | Array<number | string | null>;
    'backface-visibility': string|null | Array<number | string | null>;
    'background-attachment': string|null | Array<number | string | null>;
    'background-clip': string|null | Array<number | string | null>;
    'background-color': string|null | Array<number | string | null>;
    'background-image': string|null | Array<number | string | null>;
    'background-origin': string|null | Array<number | string | null>;
    'background-position': string|null | Array<number | string | null>;
    'background-position-x': string|null | Array<number | string | null>;
    'background-position-y': string|null | Array<number | string | null>;
    'background-repeat': string|null | Array<number | string | null>;
    'background-size': string|null | Array<number | string | null>;
    'baseline-shift': string|null | Array<number | string | null>;
    'border-bottom': string|null | Array<number | string | null>;
    'border-bottom-color': string|null | Array<number | string | null>;
    'border-bottom-left-radius': string|null | Array<number | string | null>;
    'border-bottom-right-radius': string|null | Array<number | string | null>;
    'border-bottom-style': string|null | Array<number | string | null>;
    'border-bottom-width': string|null | Array<number | string | null>;
    'border-collapse': string|null | Array<number | string | null>;
    'border-color': string|null | Array<number | string | null>;
    'border-image': string|null | Array<number | string | null>;
    'border-image-outset': string|null | Array<number | string | null>;
    'border-image-repeat': string|null | Array<number | string | null>;
    'border-image-slice': string|null | Array<number | string | null>;
    'border-image-source': string|null | Array<number | string | null>;
    'border-image-width': string|null | Array<number | string | null>;
    'border-left': string|null | Array<number | string | null>;
    'border-left-color': string|null | Array<number | string | null>;
    'border-left-style': string|null | Array<number | string | null>;
    'border-left-width': string|null | Array<number | string | null>;
    'border-radius': string|null | Array<number | string | null>;
    'border-right': string|null | Array<number | string | null>;
    'border-right-color': string|null | Array<number | string | null>;
    'border-right-style': string|null | Array<number | string | null>;
    'border-right-width': string|null | Array<number | string | null>;
    'border-spacing': string|null | Array<number | string | null>;
    'border-style': string|null | Array<number | string | null>;
    'border-top': string|null | Array<number | string | null>;
    'border-top-color': string|null | Array<number | string | null>;
    'border-top-left-radius': string|null | Array<number | string | null>;
    'border-top-right-radius': string|null | Array<number | string | null>;
    'border-top-style': string|null | Array<number | string | null>;
    'border-top-width': string|null | Array<number | string | null>;
    'border-width': string|null | Array<number | string | null>;
    'box-shadow': string|null | Array<number | string | null>;
    'box-sizing': string|null | Array<number | string | null>;
    'break-after': string|null | Array<number | string | null>;
    'break-before': string|null | Array<number | string | null>;
    'break-inside': string|null | Array<number | string | null>;
    'caption-side': string|null | Array<number | string | null>;
    'clip-path': string|null | Array<number | string | null>;
    'clip-rule': string|null | Array<number | string | null>;
    'color-interpolation-filters': string|null | Array<number | string | null>;
    'column-count': any | Array<number | string | null>;
    'column-fill': string|null | Array<number | string | null>;
    'column-gap': any | Array<number | string | null>;
    'column-rule': string|null | Array<number | string | null>;
    'column-rule-color': any | Array<number | string | null>;
    'column-rule-style': string|null | Array<number | string | null>;
    'column-rule-width': any | Array<number | string | null>;
    'column-span': string|null | Array<number | string | null>;
    'column-width': any | Array<number | string | null>;
    'counter-increment': string|null | Array<number | string | null>;
    'counter-reset': string|null | Array<number | string | null>;
    'css-float': string|null | Array<number | string | null>;
    'css-text': string | Array<number | string | null>;
    'dominant-baseline': string|null | Array<number | string | null>;
    'empty-cells': string|null | Array<number | string | null>;
    'enable-background': string|null | Array<number | string | null>;
    'fill-opacity': string|null | Array<number | string | null>;
    'fill-rule': string|null | Array<number | string | null>;
    'flex-basis': string|null | Array<number | string | null>;
    'flex-direction': string|null | Array<number | string | null>;
    'flex-flow': string|null | Array<number | string | null>;
    'flex-grow': string|null | Array<number | string | null>;
    'flex-shrink': string|null | Array<number | string | null>;
    'flex-wrap': string|null | Array<number | string | null>;
    'flood-color': string|null | Array<number | string | null>;
    'flood-opacity': string|null | Array<number | string | null>;
    'font-family': string|null | Array<number | string | null>;
    'font-feature-settings': string|null | Array<number | string | null>;
    'font-size': string|null | Array<number | string | null>;
    'font-size-adjust': string|null | Array<number | string | null>;
    'font-stretch': string|null | Array<number | string | null>;
    'font-style': string|null | Array<number | string | null>;
    'font-variant': string|null | Array<number | string | null>;
    'font-weight': string|null | Array<number | string | null>;
    'glyph-orientation-horizontal': string|null | Array<number | string | null>;
    'glyph-orientation-vertical': string|null | Array<number | string | null>;
    'grid-area': string|null | Array<number | string | null>;
    'grid-auto-columns': string|null | Array<number | string | null>;
    'grid-auto-flow': string|null | Array<number | string | null>;
    'grid-auto-rows': string|null | Array<number | string | null>;
    'grid-column': string|null | Array<number | string | null>;
    'grid-column-end': string|null | Array<number | string | null>;
    'grid-column-gap': string|null | Array<number | string | null>;
    'grid-column-start': string|null | Array<number | string | null>;
    'grid-gap': string|null | Array<number | string | null>;
    'grid-row': string|null | Array<number | string | null>;
    'grid-row-end': string|null | Array<number | string | null>;
    'grid-row-gap': string|null | Array<number | string | null>;
    'grid-row-start': string|null | Array<number | string | null>;
    'grid-template': string|null | Array<number | string | null>;
    'grid-template-areas': string|null | Array<number | string | null>;
    'grid-template-columns': string|null | Array<number | string | null>;
    'grid-template-rows': string|null | Array<number | string | null>;
    'ime-mode': string|null | Array<number | string | null>;
    'justify-content': string|null | Array<number | string | null>;
    'justify-items': string|null | Array<number | string | null>;
    'justify-self': string|null | Array<number | string | null>;
    'layout-grid': string|null | Array<number | string | null>;
    'layout-grid-char': string|null | Array<number | string | null>;
    'layout-grid-line': string|null | Array<number | string | null>;
    'layout-grid-mode': string|null | Array<number | string | null>;
    'layout-grid-type': string|null | Array<number | string | null>;
    'readonlylength': number | Array<number | string | null>;
    'letter-spacing': string|null | Array<number | string | null>;
    'lighting-color': string|null | Array<number | string | null>;
    'line-break': string|null | Array<number | string | null>;
    'line-height': string|null | Array<number | string | null>;
    'list-style': string|null | Array<number | string | null>;
    'list-style-image': string|null | Array<number | string | null>;
    'list-style-position': string|null | Array<number | string | null>;
    'list-style-type': string|null | Array<number | string | null>;
    'margin-bottom': string|null | Array<number | string | null>;
    'margin-left': string|null | Array<number | string | null>;
    'margin-right': string|null | Array<number | string | null>;
    'margin-top': string|null | Array<number | string | null>;
    'marker-end': string|null | Array<number | string | null>;
    'marker-mid': string|null | Array<number | string | null>;
    'marker-start': string|null | Array<number | string | null>;
    'mask-image': string|null | Array<number | string | null>;
    'max-height': string|null | Array<number | string | null>;
    'max-width': string|null | Array<number | string | null>;
    'min-height': string|null | Array<number | string | null>;
    'min-width': string|null | Array<number | string | null>;
    'ms-content-zoom-chaining': string|null | Array<number | string | null>;
    'ms-content-zoom-limit': string|null | Array<number | string | null>;
    'ms-content-zoom-limit-max': any | Array<number | string | null>;
    'ms-content-zoom-limit-min': any | Array<number | string | null>;
    'ms-content-zoom-snap': string|null | Array<number | string | null>;
    'ms-content-zoom-snap-points': string|null | Array<number | string | null>;
    'ms-content-zoom-snap-type': string|null | Array<number | string | null>;
    'ms-content-zooming': string|null | Array<number | string | null>;
    'ms-flow-from': string|null | Array<number | string | null>;
    'ms-flow-into': string|null | Array<number | string | null>;
    'ms-font-feature-settings': string|null | Array<number | string | null>;
    'ms-grid-column': any | Array<number | string | null>;
    'ms-grid-column-align': string|null | Array<number | string | null>;
    'ms-grid-column-span': any | Array<number | string | null>;
    'ms-grid-columns': string|null | Array<number | string | null>;
    'ms-grid-row': any | Array<number | string | null>;
    'ms-grid-row-align': string|null | Array<number | string | null>;
    'ms-grid-row-span': any | Array<number | string | null>;
    'ms-grid-rows': string|null | Array<number | string | null>;
    'ms-high-contrast-adjust': string|null | Array<number | string | null>;
    'ms-hyphenate-limit-chars': string|null | Array<number | string | null>;
    'ms-hyphenate-limit-lines': any | Array<number | string | null>;
    'ms-hyphenate-limit-zone': any | Array<number | string | null>;
    'ms-hyphens': string|null | Array<number | string | null>;
    'ms-ime-align': string|null | Array<number | string | null>;
    'ms-overflow-style': string|null | Array<number | string | null>;
    'ms-scroll-chaining': string|null | Array<number | string | null>;
    'ms-scroll-limit': string|null | Array<number | string | null>;
    'ms-scroll-limit-x-max': any | Array<number | string | null>;
    'ms-scroll-limit-x-min': any | Array<number | string | null>;
    'ms-scroll-limit-y-max': any | Array<number | string | null>;
    'ms-scroll-limit-y-min': any | Array<number | string | null>;
    'ms-scroll-rails': string|null | Array<number | string | null>;
    'ms-scroll-snap-points-x': string|null | Array<number | string | null>;
    'ms-scroll-snap-points-y': string|null | Array<number | string | null>;
    'ms-scroll-snap-type': string|null | Array<number | string | null>;
    'ms-scroll-snap-x': string|null | Array<number | string | null>;
    'ms-scroll-snap-y': string|null | Array<number | string | null>;
    'ms-scroll-translation': string|null | Array<number | string | null>;
    'ms-text-combine-horizontal': string|null | Array<number | string | null>;
    'ms-text-size-adjust': any | Array<number | string | null>;
    'ms-touch-action': string|null | Array<number | string | null>;
    'ms-touch-select': string|null | Array<number | string | null>;
    'ms-user-select': string|null | Array<number | string | null>;
    'ms-wrap-flow': string | Array<number | string | null>;
    'ms-wrap-margin': any | Array<number | string | null>;
    'ms-wrap-through': string | Array<number | string | null>;
    'object-fit': string|null | Array<number | string | null>;
    'object-position': string|null | Array<number | string | null>;
    'outline-color': string|null | Array<number | string | null>;
    'outline-offset': string|null | Array<number | string | null>;
    'outline-style': string|null | Array<number | string | null>;
    'outline-width': string|null | Array<number | string | null>;
    'overflow-x': string|null | Array<number | string | null>;
    'overflow-y': string|null | Array<number | string | null>;
    'padding-bottom': string|null | Array<number | string | null>;
    'padding-left': string|null | Array<number | string | null>;
    'padding-right': string|null | Array<number | string | null>;
    'padding-top': string|null | Array<number | string | null>;
    'page-break-after': string|null | Array<number | string | null>;
    'page-break-before': string|null | Array<number | string | null>;
    'page-break-inside': string|null | Array<number | string | null>;
    'readonlyparent-rule': CSSRule | Array<number | string | null>;
    'pen-action': string|null | Array<number | string | null>;
    'perspective-origin': string|null | Array<number | string | null>;
    'pointer-events': string|null | Array<number | string | null>;
    'row-gap': string|null | Array<number | string | null>;
    'ruby-align': string|null | Array<number | string | null>;
    'ruby-overhang': string|null | Array<number | string | null>;
    'ruby-position': string|null | Array<number | string | null>;
    'scroll-behavior': string | Array<number | string | null>;
    'stop-color': string|null | Array<number | string | null>;
    'stop-opacity': string|null | Array<number | string | null>;
    'stroke-dasharray': string|null | Array<number | string | null>;
    'stroke-dashoffset': string|null | Array<number | string | null>;
    'stroke-linecap': string|null | Array<number | string | null>;
    'stroke-linejoin': string|null | Array<number | string | null>;
    'stroke-miterlimit': string|null | Array<number | string | null>;
    'stroke-opacity': string|null | Array<number | string | null>;
    'stroke-width': string|null | Array<number | string | null>;
    'table-layout': string|null | Array<number | string | null>;
    'text-align': string|null | Array<number | string | null>;
    'text-align-last': string|null | Array<number | string | null>;
    'text-anchor': string|null | Array<number | string | null>;
    'text-combine-upright': string|null | Array<number | string | null>;
    'text-decoration': string|null | Array<number | string | null>;
    'text-indent': string|null | Array<number | string | null>;
    'text-justify': string|null | Array<number | string | null>;
    'text-kashida': string|null | Array<number | string | null>;
    'text-kashida-space': string|null | Array<number | string | null>;
    'text-overflow': string|null | Array<number | string | null>;
    'text-shadow': string|null | Array<number | string | null>;
    'text-transform': string|null | Array<number | string | null>;
    'text-underline-position': string|null | Array<number | string | null>;
    'touch-action': string | Array<number | string | null>;
    'transform-origin': string|null | Array<number | string | null>;
    'transform-style': string|null | Array<number | string | null>;
    'transition-delay': string | Array<number | string | null>;
    'transition-duration': string | Array<number | string | null>;
    'transition-property': string | Array<number | string | null>;
    'transition-timing-function': string | Array<number | string | null>;
    'unicode-bidi': string|null | Array<number | string | null>;
    'user-select': string|null | Array<number | string | null>;
    'vertical-align': string|null | Array<number | string | null>;
    'webkit-align-content': string | Array<number | string | null>;
    'webkit-align-items': string | Array<number | string | null>;
    'webkit-align-self': string | Array<number | string | null>;
    'webkit-animation': string | Array<number | string | null>;
    'webkit-animation-delay': string | Array<number | string | null>;
    'webkit-animation-direction': string | Array<number | string | null>;
    'webkit-animation-duration': string | Array<number | string | null>;
    'webkit-animation-fill-mode': string | Array<number | string | null>;
    'webkit-animation-iteration-count': string | Array<number | string | null>;
    'webkit-animation-name': string | Array<number | string | null>;
    'webkit-animation-play-state': string | Array<number | string | null>;
    'webkit-animation-timing-function': string | Array<number | string | null>;
    'webkit-appearance': string | Array<number | string | null>;
    'webkit-backface-visibility': string | Array<number | string | null>;
    'webkit-background-clip': string | Array<number | string | null>;
    'webkit-background-origin': string | Array<number | string | null>;
    'webkit-background-size': string | Array<number | string | null>;
    'webkit-border-bottom-left-radius': string | Array<number | string | null>;
    'webkit-border-bottom-right-radius': string | Array<number | string | null>;
    'webkit-border-image': string|null | Array<number | string | null>;
    'webkit-border-radius': string | Array<number | string | null>;
    'webkit-border-top-left-radius': string | Array<number | string | null>;
    'webkit-border-top-right-radius': string | Array<number | string | null>;
    'webkit-box-align': string | Array<number | string | null>;
    'webkit-box-direction': string|null | Array<number | string | null>;
    'webkit-box-flex': string | Array<number | string | null>;
    'webkit-box-ordinal-group': string | Array<number | string | null>;
    'webkit-box-orient': string|null | Array<number | string | null>;
    'webkit-box-pack': string | Array<number | string | null>;
    'webkit-box-shadow': string | Array<number | string | null>;
    'webkit-box-sizing': string | Array<number | string | null>;
    'webkit-column-break-after': string|null | Array<number | string | null>;
    'webkit-column-break-before': string|null | Array<number | string | null>;
    'webkit-column-break-inside': string|null | Array<number | string | null>;
    'webkit-column-count': any | Array<number | string | null>;
    'webkit-column-gap': any | Array<number | string | null>;
    'webkit-column-rule': string|null | Array<number | string | null>;
    'webkit-column-rule-color': any | Array<number | string | null>;
    'webkit-column-rule-style': string|null | Array<number | string | null>;
    'webkit-column-rule-width': any | Array<number | string | null>;
    'webkit-column-span': string|null | Array<number | string | null>;
    'webkit-column-width': any | Array<number | string | null>;
    'webkit-columns': string|null | Array<number | string | null>;
    'webkit-filter': string | Array<number | string | null>;
    'webkit-flex': string | Array<number | string | null>;
    'webkit-flex-basis': string | Array<number | string | null>;
    'webkit-flex-direction': string | Array<number | string | null>;
    'webkit-flex-flow': string | Array<number | string | null>;
    'webkit-flex-grow': string | Array<number | string | null>;
    'webkit-flex-shrink': string | Array<number | string | null>;
    'webkit-flex-wrap': string | Array<number | string | null>;
    'webkit-justify-content': string | Array<number | string | null>;
    'webkit-mask': string | Array<number | string | null>;
    'webkit-mask-box-image': string | Array<number | string | null>;
    'webkit-mask-box-image-outset': string | Array<number | string | null>;
    'webkit-mask-box-image-repeat': string | Array<number | string | null>;
    'webkit-mask-box-image-slice': string | Array<number | string | null>;
    'webkit-mask-box-image-source': string | Array<number | string | null>;
    'webkit-mask-box-image-width': string | Array<number | string | null>;
    'webkit-mask-clip': string | Array<number | string | null>;
    'webkit-mask-composite': string | Array<number | string | null>;
    'webkit-mask-image': string | Array<number | string | null>;
    'webkit-mask-origin': string | Array<number | string | null>;
    'webkit-mask-position': string | Array<number | string | null>;
    'webkit-mask-repeat': string | Array<number | string | null>;
    'webkit-mask-size': string | Array<number | string | null>;
    'webkit-order': string | Array<number | string | null>;
    'webkit-perspective': string | Array<number | string | null>;
    'webkit-perspective-origin': string | Array<number | string | null>;
    'webkit-tap-highlight-color': string|null | Array<number | string | null>;
    'webkit-text-fill-color': string | Array<number | string | null>;
    'webkit-text-size-adjust': string | Array<number | string | null>;
    'webkit-text-stroke': string | Array<number | string | null>;
    'webkit-text-stroke-color': string | Array<number | string | null>;
    'webkit-text-stroke-width': string | Array<number | string | null>;
    'webkit-transform': string | Array<number | string | null>;
    'webkit-transform-origin': string | Array<number | string | null>;
    'webkit-transform-style': string | Array<number | string | null>;
    'webkit-transition': string | Array<number | string | null>;
    'webkit-transition-delay': string | Array<number | string | null>;
    'webkit-transition-duration': string | Array<number | string | null>;
    'webkit-transition-property': string | Array<number | string | null>;
    'webkit-transition-timing-function': string | Array<number | string | null>;
    'webkit-user-modify': string|null | Array<number | string | null>;
    'webkit-user-select': string|null | Array<number | string | null>;
    'webkit-writing-mode': string|null | Array<number | string | null>;
    'white-space': string|null | Array<number | string | null>;
    'word-break': string|null | Array<number | string | null>;
    'word-spacing': string|null | Array<number | string | null>;
    'word-wrap': string|null | Array<number | string | null>;
    'writing-mode': string|null | Array<number | string | null>;
    'z-index': string|null | Array<number | string | null>;
}